#!/bin/bash
#
# Build PXB inside a pxc-build container.
#
# Usage: ./docker/run-build <SOURCE_IMAGE> <ARCH>
#   SOURCE_IMAGE  docker tag (oraclelinux:9, ubuntu:noble, asan, etc.)
#   ARCH          x86_64 | aarch64   (REQUIRED, no default)
#
# Image pulled: public.ecr.aws/e7j3v3n0/pxc-build:<distro>[-aarch64]

set -o errexit
set -o xtrace

ROOT_DIR=$(cd $(dirname $0)/../sources; pwd -P)
SCRIPTS_DIR=$(cd $(dirname $0)/../local; pwd -P)
SOURCE_IMAGE=${1:-oraclelinux:9}
ARCH=${2:?ARCH is required (x86_64 or aarch64)}

case "${ARCH}" in
    x86_64)  ARCH_SUFFIX="" ;;
    aarch64) ARCH_SUFFIX="-aarch64" ;;
    *) echo "ERROR: unsupported ARCH='${ARCH}', expected x86_64 or aarch64" >&2; exit 1 ;;
esac

if [[ ${SOURCE_IMAGE} == 'asan' ]]; then
    SOURCE_IMAGE='oraclelinux:9'
    ASAN_SWITCH=ON
fi

docker run --rm \
    --cap-add SYS_PTRACE \
    --mount type=bind,source=${ROOT_DIR},destination=/tmp/pxb \
    --mount type=bind,source=${SCRIPTS_DIR},destination=/tmp/scripts \
    public.ecr.aws/e7j3v3n0/pxc-build:${SOURCE_IMAGE//[:\/]/-}${ARCH_SUFFIX} \
    sh -c "
    set -o errexit
    set -o xtrace

    export CMAKE_BUILD_TYPE='${CMAKE_BUILD_TYPE}'
    export CMAKE_OPTS='${CMAKE_OPTS}'
    export MAKE_OPTS='${MAKE_OPTS}'
    export ASAN_SWITCH='${ASAN_SWITCH}'
    export DOCKER_OS='${DOCKER_OS//:/-}'

    mkdir /tmp/results
    cp -r /tmp/source_downloads /tmp/results/source_downloads
    sudo chown -R mysql:mysql /tmp/pxb
    bash -x /tmp/scripts/build-binary /tmp/results /tmp/pxb

    sudo rm -rf /tmp/pxb/results
    sudo mkdir /tmp/pxb/results
    sudo mv /tmp/results/*.tar.gz /tmp/pxb/results/
    sudo chown -R $(id -u):$(id -g) /tmp/pxb/results
"
