#!/bin/bash

set -o errexit
set -o xtrace

ROOT_DIR=$(cd $(dirname $0)/../sources/pxc; pwd -P)
SCRIPTS_DIR=$(cd $(dirname $0)/../local; pwd -P)
SOURCE_IMAGE=${1:-centos:7}
WORKER_NO=${2:-0}
DOCKER_SHM_SIZE=${3:-32G}

if [[ ${CI_FS_MTR} == 'yes' ]]; then
    CI_FS_DOCKER_FLAG="--mount type=bind,source=/mnt/ci_disk_dir_${CMAKE_BUILD_TYPE},destination=/tmp/ci_disk_dir"
fi

docker run --rm --shm-size=${DOCKER_SHM_SIZE} \
    --tmpfs /dev/shm:rw,exec,size=${DOCKER_SHM_SIZE} \
    --security-opt seccomp=unconfined \
    --sysctl net.ipv6.conf.lo.disable_ipv6=0 \
    --mount type=bind,source=${ROOT_DIR},destination=/tmp/pxc \
    --mount type=bind,source=${SCRIPTS_DIR},destination=/tmp/scripts \
    ${CI_FS_DOCKER_FLAG} \
    public.ecr.aws/e7j3v3n0/pxc-build:${SOURCE_IMAGE//[:\/]/-} \
    sh -c "
    set -o errexit
    set -o xtrace

    export CMAKE_BUILD_TYPE='${CMAKE_BUILD_TYPE}'
    export ANALYZER_OPTS='${ANALYZER_OPTS}'
    export DEFAULT_TESTING='${DEFAULT_TESTING}'
    export MTR_ARGS='${MTR_ARGS}'
    export MTR_REPEAT='${MTR_REPEAT}'
    export MTR_VAULT_TOKEN='${MTR_VAULT_TOKEN}'
    export FULL_MTR='${FULL_MTR}'
    export GALERA_PARALLEL_RUN='${GALERA_PARALLEL_RUN}'
    export MTR_SUITES='${MTR_SUITES}'
    export MTR_STANDALONE_TESTS='${MTR_STANDALONE_TESTS}'
    export MTR_STANDALONE_TESTS_PARALLEL='${MTR_STANDALONE_TESTS_PARALLEL}'
    export MTR_STANDALONE_TESTS_TESTCASE_TIMEOUT='${MTR_STANDALONE_TESTS_TESTCASE_TIMEOUT}'
    export CI_FS_MTR='${CI_FS_MTR}'
    export DOCKER_OS='${DOCKER_OS//:/-}'
    export WORKER_NO='${WORKER_NO}'
    export PXB_PREV_LTS_TARGET_DIR='${PXB_PREV_LTS_VERSION_TARGET_DIR}'
    export PXB_A_TARGET_DIR='${PXB_PREV_VERSION_TARGET_DIR}'
    export PXB_B_TARGET_DIR='${PXB_THIS_VERSION_TARGET_DIR}'

    mkdir /tmp/results
    cp /tmp/pxc/results/*.tar.gz /tmp/results
    cp -ra /tmp/pxc/results/pxb_prev_LTS /tmp/results/pxb_prev_LTS
    cp -ra /tmp/pxc/results/pxb_A /tmp/results/pxb_A ||:
    cp -ra /tmp/pxc/results/pxb_B /tmp/results/pxb_B ||:

    bash -x /tmp/scripts/test-binary-pxc-parallel-mtr /tmp/results

    mkdir /tmp/results/log
    rsync -a --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' /tmp/results/PXC/mysql-test/mtr_var /tmp/results/log
    pwd
    ls -la
    sudo tar -C /tmp/results/log -czf "pxc80-test-mtr_logs-${WORKER_NO}.tar.gz" mtr_var

    sudo mv ./pxc80-test-mtr_logs-${WORKER_NO}.tar.gz /tmp/pxc/results/ ||:
    sudo mv /tmp/results/*.xml /tmp/pxc/results/ ||:
    sudo mv /tmp/results/mtr-test.log /tmp/pxc/results/mtr-test-w_${WORKER_NO}.log ||:

    # In case of Valgrind build, do some more logs processing
    case '${ANALYZER_OPTS}' in
      *WITH_VALGRIND=ON*)
        cd /tmp/pxc/results
        sudo grep -A16 'Conditional jump or move depends on uninitialised' mtr-test-w_${WORKER_NO}.log | sudo tee mtr-test-valgrind-ConditionalJump-w_${WORKER_NO}.log > /dev/null || :
        sudo grep -A16 'are definitely lost' mtr-test-w_${WORKER_NO}.log | sudo tee mtr-test-valgrind-definitelyLost-w_${WORKER_NO}.log > /dev/null || :
        sudo grep -B128 -A128 'Invalid read of size' mtr-test-w_${WORKER_NO}.log | sudo tee mtr-test-valgrind-InvalidRead-w_${WORKER_NO}.log > /dev/null || :

        sudo bash -x -c '
          wget https://raw.githubusercontent.com/inikep/ps-build/refs/heads/8.0/jenkins/jenkins-common.sh ||:
          source jenkins-common.sh ||:
          filter_valgrind_log mtr-test-w_${WORKER_NO}.log mtr-test-w_${WORKER_NO}.log.processed ||:
          mv -f mtr-test-w_${WORKER_NO}.log.processed mtr-test-w_${WORKER_NO}.log ||:
        '
    ;;
    esac

    # In case of ASAN build, do some more logs processing
    case '${ANALYZER_OPTS}' in
      *WITH_ASAN=ON*)
        cd /tmp/pxc/results
        sudo grep -A16 'ERROR: .*Sanitizer' mtr-test-w_${WORKER_NO}.log | sudo tee mtr-test-Errors-Sanitizers-w_${WORKER_NO}.log > /dev/null || :
        sudo grep -A16 'ERROR: AddressSanitizer' mtr-test-w_${WORKER_NO}.log | sudo tee mtr-test-Errors-AddressSanitizer-w_${WORKER_NO}.log > /dev/null || :
        sudo grep -A16 'ERROR: LeakSanitizer' mtr-test-w_${WORKER_NO}.log | sudo tee mtr-test-Errors-LeakSanitizer-w_${WORKER_NO}.log > /dev/null || :
    ;;
    esac



    sudo chown $(id -u):$(id -g) /tmp/pxc/results/* ||:
"
