#!/bin/bash

set -o errexit
set -o xtrace

ROOT_DIR=$(cd $(dirname $0)/../sources/pxc56; pwd -P)
SCRIPTS_DIR=$(cd $(dirname $0)/../local; pwd -P)
SOURCE_IMAGE=${1:-centos:7}

docker run --rm \
    --cap-add SYS_PTRACE \
    --mount type=bind,source=${ROOT_DIR},destination=/tmp/pxc56 \
    --mount type=bind,source=${SCRIPTS_DIR},destination=/tmp/scripts \
    public.ecr.aws/e7j3v3n0/pxc-build:${SOURCE_IMAGE//[:\/]/-} \
    sh -c "
    set -o errexit
    set -o xtrace

    export JOB_CMAKE='${JOB_CMAKE}'
    export COMPILER='${COMPILER}'
    export CMAKE_BUILD_TYPE='${CMAKE_BUILD_TYPE}'
    export CMAKE_OPTS='${CMAKE_OPTS}'
    export MAKE_OPTS='${MAKE_OPTS}'
    export BUILD_COMMENT='${BUILD_COMMENT}'
    export TAG='${TAG}'
    export DIST_NAME='${DIST_NAME}'
    export SSL_VER='${SSL_VER}'

    mkdir /tmp/results
   
    cp -r /tmp/source_downloads /tmp/results/source_downloads
    sudo chown -R mysql:mysql /tmp/pxc56/wsrep /tmp/pxc56/mysql-test /tmp/pxc56/target || :
    bash -x /tmp/scripts/build-binary-pxc56 /tmp/results /tmp/pxc56

    sudo rm -rf /tmp/pxc56/results
    sudo mkdir /tmp/pxc56/results
    sudo mv /tmp/results/*.tar.gz /tmp/pxc56/results/
    sudo chown -R $(id -u):$(id -g) /tmp/pxc56/results /tmp/pxc56/wsrep /tmp/pxc56/mysql-test /tmp/pxc56/target
"
