#!/bin/bash

set -o errexit
set -o xtrace

ROOT_DIR=$(cd $(dirname $0)/../sources/pxc; pwd -P)
SCRIPTS_DIR=$(cd $(dirname $0)/../local; pwd -P)
SOURCE_IMAGE=${1:-centos:7}

docker run --rm \
    --security-opt seccomp=unconfined \
    --mount type=bind,source=${ROOT_DIR},destination=/tmp/pxc \
    --mount type=bind,source=${SCRIPTS_DIR},destination=/tmp/scripts \
    perconalab/pxc-build:${SOURCE_IMAGE//[:\/]/-} \
    sh -c "
    set -o errexit
    set -o xtrace

    export CMAKE_BUILD_TYPE='${CMAKE_BUILD_TYPE}'
    export ANALYZER_OPTS='${ANALYZER_OPTS}'
    export DEFAULT_TESTING='${DEFAULT_TESTING}'
    export QA_ARGS='${QA_ARGS}'

    mkdir /tmp/results
    cp /tmp/pxc/results/*.tar.gz /tmp/results
	
    bash -x /tmp/scripts/test-qa-framework-pxc57 /tmp/results
    rsync -a --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' /tmp/results/failed_logs
    sudo tar czfP "pxc-qa-framework-run_logs.tar.gz" /tmp/results/failed_logs 

    sudo mv ./pxc-qa-framework-run_logs.tar.gz /tmp/pxc/results/
    sudo mv /tmp/results/*.output /tmp/results/*.xml  /tmp/results/pxc-qa/*.out /tmp/pxc/results/
    sudo chown $(id -u):$(id -g) /tmp/pxc/results/*.output /tmp/pxc/results/*.out /tmp/pxc/results/*.xml
"
