#!/bin/bash

set -o errexit
set -o xtrace

status=0

function process_tests_output {
# parameters are:
  local infile=${1}

  local fail_cnt

# For now just a simple decision: pass/fail
  fail_cnt=`grep -c "\+ FAIL" $infile` || true
  echo "Failures count: $fail_cnt"
  if [[ "$fail_cnt" != "0" ]] ; then
    status=1
  fi
}

ROOT_DIR=$(cd $(dirname $0)/../sources/orchestrator; pwd -P)

export TARBALL_URL=${PS_TARBALL}

cd ${ROOT_DIR}
script/dock test-no-it | tee integration-tests.log

process_tests_output "integration-tests.log"

echo "Exiting with status: $status"
exit $status