#!/bin/bash

set -e
set -x

status=0

RESULT_FILE=${RESULT_FILE:-system-tests.result}

function process_tests_output {
# parameters are:
  local infile=${1}
  local not_failed=`grep -c "^FAILED:\s*0/" $infile`
  local not_unstable=`grep -c "^UNSTABLE:\s*0/" $infile`
  local result='SUCCESS'
  
  if [ ${not_failed} -eq 0 ] ; then
    result='FAILURE'
  elif [ ${not_unstable} -eq 0 ] ; then
    result='UNSTABLE'
  fi
  echo ${result} > ${RESULT_FILE} 
}

ROOT_DIR=$(cd $(dirname $0)/../sources/orchestrator; pwd -P)

export RUN_TESTS=YES
export ALLOW_TESTS_FAILURES=YES
export TARBALL_URL=${PS_TARBALL}
export CI_ENV_REPO=${CI_ENV_GIT_REPO}
export CI_ENV_BRANCH=${CI_ENV_BRANCH}

cd ${ROOT_DIR}
script/dock system-no-it | tee system-tests.log

process_tests_output "system-tests.log"