#!/bin/bash

set -e
set -x

status=0

RESULT_FILE=${RESULT_FILE:-integration-tests.result}

function process_tests_output {
# parameters are:
  local infile=${1}
  local fail_cnt
  local result='SUCCESS'

# For now just a simple decision: pass/fail
  fail_cnt=`grep -c "\+ FAIL" $infile` || true
  if [[ "$fail_cnt" != "0" ]] ; then
    result='FAILURE'
  else
    result='SUCCESS'
  fi
  echo ${result} > ${RESULT_FILE} 
}

ROOT_DIR=$(cd $(dirname $0)/../sources/orchestrator; pwd -P)

export TARBALL_URL=${PS_TARBALL}

cd ${ROOT_DIR}
script/dock test-no-it | tee integration-tests.log

process_tests_output "integration-tests.log"