#!/bin/bash

#  possible vars:
#      PXB80_REPO
#      PXB80_BRANCH
#      PXB24_REPO
#      PXB24_BRANCH

set -o errexit
set -o xtrace

SOURCE_NAME=${1:-'ALL'}

ROOT_DIR=$(cd $(dirname $0)/..; pwd -P)/sources

if [ ! -d "${ROOT_DIR}" ]; then
    mkdir -p ${ROOT_DIR}
fi

# ==================== PXB80 ====================

if [ "$SOURCE_NAME" == 'PXB80' -o "$SOURCE_NAME" == 'ALL' ]; then
    PXB80_ROOT_DIR="${ROOT_DIR}/pxb80"

    sudo rm -rf ${PXB80_ROOT_DIR}

    git clone "${PXB80_REPO:-https://github.com/percona/percona-xtrabackup}" "${PXB80_ROOT_DIR}"

    pushd $PXB80_ROOT_DIR
        if [ -n "${PXB80_REPO}" ]; then
            git remote set-url origin "${PXB80_REPO}"
            git fetch --all
        fi

        git reset --hard
        git clean -xdf

        if [ -n "${PXB80_BRANCH}" ]; then
            git checkout "${PXB80_BRANCH}"
            git checkout -b "tag-${PXB80_BRANCH}"
        fi
        if [ -n "${PXB80_REPO}" -a -n "${PXB80_BRANCH}" ]; then
            git pull origin ${PXB80_BRANCH}
        fi
     popd
fi

# ==================== PXB24 ====================

if [ "$SOURCE_NAME" == 'PXB24' -o "$SOURCE_NAME" == 'ALL' ]; then
    PXB24_ROOT_DIR="${ROOT_DIR}/pxb24"
 
    sudo rm -rf ${PXB24_ROOT_DIR}

    git clone "${PXB24_REPO:-https://github.com/percona/percona-xtrabackup}" "${PXB24_ROOT_DIR}"

    pushd $PXB24_ROOT_DIR
        if [ -n "${PXB24_REPO}" ]; then
            git remote set-url origin "${PXB24_REPO}"
            git fetch --all
        fi

        git reset --hard
        git clean -xdf
        if [ -n "${PXB24_BRANCH}" ]; then
            git checkout "${PXB24_BRANCH}"
            git checkout -b "tag-${PXB24_BRANCH}"
        fi
        if [ -n "${PXB24_REPO}" -a -n "${PXB24_BRANCH}" ]; then
            git pull origin ${PXB24_BRANCH}
        fi
    popd
fi
