#!/bin/bash
#
# Execute this tool to test binary releases
#
#  possible jenkins vars:
#      CMAKE_BUILD_TYPE = (RelWithDebInfo Debug)
#      PAT_TAG

set -o errexit
set -o xtrace

if [ -f /usr/bin/yum ]; then
    RHEL=$(rpm --eval %rhel)
    if [[ $RHEL -eq 8 ]]; then
        sudo yum -y install cmake python2 gnutls-devel libtool || true

    fi
    sudo yum -y install wget
    if [[ $RHEL -eq 7 ]]; then
      sudo yum -y install automake bzip2 cmake3 make gcc-c++ gcc git openssl openssl-devel gnutls gnutls-devel libtool patch
      if [ -f /usr/bin/cmake3 ]; then
        sudo mv /usr/bin/cmake /usr/bin/cmake2
        sudo ln -s /usr/bin/cmake3 /usr/bin/cmake
      fi
    fi
fi

if [ $RHEL = 8 ]; then
    sudo ln -s /usr/bin/python2.7 /usr/bin/python || true
    sudo yum remove -y cmake
    sudo wget https://github.com/Kitware/CMake/releases/download/v3.19.8/cmake-3.19.8.tar.gz
    sudo tar -zxvf cmake-3.19.8.tar.gz
    cd cmake-3.19.8/
    sudo ./bootstrap
    sudo make install
    PATH=$PATH:/usr/local/bin
    cmake --version
fi

sudo wget https://dl.google.com/go/go1.17.7.linux-amd64.tar.gz
sudo tar -C /usr/local/ -xzf go1.17.7.linux-amd64.tar.gz
sudo cp /usr/local/go/bin/go /usr/local/bin/go

WORKDIR_ABS=$(cd ${1:-./build/proxysql}; pwd -P)
SOURCE_DIR=$(cd ${2:-./build/proxysql}; pwd -P)

status=0
sudo sed -i "4 a PAT_TAG=${PAT_TAG}" ${SOURCE_DIR}/proxysql-packaging/scripts/build_binary.sh
[ -f /opt/rh/devtoolset-8/enable ] && source /opt/rh/devtoolset-8/enable
sudo bash -x ${SOURCE_DIR}/proxysql-packaging/scripts/build_binary.sh ${WORKDIR_ABS} || status=$?
exit $status
