#!/bin/bash
if [[ -f /usr/bin/yum ]]; then
    export RHEL="$(rpm --eval %rhel)"
    sudo yum -y install wget
    sudo wget -O /etc/yum.repos.d/percona-dev.repo http://jenkins.percona.com/yum-repo/percona-dev.repo
    sudo yum -y install https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    sudo percona-release enable tools testing
    if [ "${RHEL}" -eq 6 ]; then
        sudo yum -y install perautomake bzip2 cmake make g++ gcc git openssl openssl-devel gnutls libtool patchcona-devtoolset-gcc percona-devtoolset-binutils percona-devtoolset-gcc-c++
        sudo yum -y install gnutls-devel libtool || true
        sudo yum -y install epel-release
        sudo sed -i 's/mirrorlist=https/mirrorlist=http/' /etc/yum.repos.d/epel.repo
        sudo yum -y install http://repo.okay.com.mx/centos/6/x86_64/release/okay-release-1-1.noarch.rpm || true
        sudo yum -y upgrade automake autoconf
    fi
    sudo yum -y install cmake make gcc gcc-c++ rpm-build openssl-devel libmicrohttpd-devel
    sudo yum -y install automake bzip2 cmake make gcc-c++ gcc git openssl openssl-devel gnutls gnutls-devel libtool patch patchelf
fi

if [[ -f /usr/bin/apt-get ]]; then
    sudo apt-get update && sudo apt-get -y install lsb-release gnupg2
    export DEBIAN_VERSION="$(lsb_release -sc)"
    echo 'deb http://jenkins.percona.com/apt-repo/ ${DEBIAN_VERSION} main' > percona-dev.list
    sudo mv -f percona-dev.list /etc/apt/sources.list.d/
    wget -q -O - http://jenkins.percona.com/apt-repo/8507EFA5.pub | sudo apt-key add -
    wget -q -O - http://jenkins.percona.com/apt-repo/CD2EFD2A.pub | sudo apt-key add -
    wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb && sudo dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
    sudo percona-release enable tools testing
    sudo apt-get update
    sudo apt-get -y install build-essential devscripts
    # deps from spec files
    sudo apt-get -y install debhelper pkg-config cmake dh-systemd
    # missing build deps
    sudo apt-get -y install libssl-dev gawk lynx zlib1g-dev make
    sudo apt-get -y purge librtmp-dev || true
    sudo apt-get -y install automake bzip2 cmake make g++ gcc git openssl libssl-dev libgnutls28-dev libtool patch patchelf
fi
