#!/bin/bash

set -o errexit
set -o xtrace

ROOT_DIR=$(cd $(dirname $0)/sources/proxysql; pwd -P)
SCRIPTS_DIR=$(cd $(dirname $0) && pwd -P)
SOURCE_IMAGE=${1:-centos:7}

docker run --rm \
    --cap-add SYS_PTRACE \
    --mount type=bind,source=${ROOT_DIR},destination=/tmp/proxysql \
    --mount type=bind,source=${SCRIPTS_DIR},destination=/tmp/scripts \
    public.ecr.aws/e7j3v3n0/pxc-build:${SOURCE_IMAGE//[:\/]/-} \
    sh -c "
    set -o errexit
    set -o xtrace
    export PAT_REPO='${PAT_REPO}'
    export PAT_TAG='${PAT_TAG}'

    sudo wget -q https://golang.org/dl/go1.16.3.linux-amd64.tar.gz
    sudo tar -C /usr/local -xzf go1.16.3.linux-amd64.tar.gz
    export PATH=$PATH:/bin:/usr/local/go/bin
    go version

    mkdir /tmp/results
    bash -x  /tmp/scripts/build-binary-proxysql /tmp/results /tmp/proxysql
    sudo rm -rf /tmp/proxysql/results
    sudo mkdir /tmp/proxysql/results
    ls -la /tmp/results/
    sudo mv /tmp/results/*.tar.gz /tmp/proxysql/results/
    sudo chown -R $(id -u):$(id -g) /tmp/proxysql/results
"
