#!/bin/bash
#
# Execute this tool to test binary releases
#
#  possible jenkins vars:
#      CMAKE_BUILD_TYPE = (RelWithDebInfo Debug)
#      DEFAULT_TESTING = (yes no)
#      QA_ARGS
#      PXC_VERSION = (PXC57 PXC80 PXC84)

set -o errexit
set -o xtrace

if [ -f /usr/bin/yum ]; then
  RHEL=$(rpm --eval %rhel)
  if [[ $RHEL -eq 8 ]]; then
     sudo dnf module disable mysql -y
  fi
fi

function process_proxysql_output {
# parameters are:
  local TESTSUITE=${1}
  local INFILE=${2}
  local OUTFILE=${3}
  export LC_ALL=C
  cat proxysql_qa.output | grep 'ok \|not ok' | gawk 'BEGIN     { print "<testsuite name=\"@@TESTSUITE@@\" tests=\"@@PASSED@@\" failures=\"@@FAILURES@@\">" }
      $1 ~ /ok/     { printf "\t<testcase name=\"%s\"><passed/></testcase>\n", $0}
      $1 ~ /not/    { printf "\t<testcase name=\"%s\"><failure/></testcase>\n", $0}
      END { print "</testsuite>" }' > ${OUTFILE}

  PASSED=$(grep -c 'name=\"ok' ${OUTFILE} ||:)
  FAILURES=$(grep -c '<failure/>' ${OUTFILE} ||:)

  sed -i.bak -e "s:@@TESTSUITE@@:${TESTSUITE}:g" ${OUTFILE}
  sed -i.bak -e "s:@@PASSED@@:${PASSED}:g" ${OUTFILE}
  sed -i.bak -e "s:@@FAILURES@@:${FAILURES}:g" ${OUTFILE}
}

function enable_repo {
# parameters are:
  local repo_name=$1
  local repo_type=$2

  sudo percona-release enable $repo_name $repo_type
}

function install_package {
# parameters are stored in array varible:
  local -a pkg_name_arr=("$@")

  if [ -f /usr/bin/yum ]; then
    for file in ${pkg_name_arr[@]}; do
      sudo yum install -y $file
    done
  elif [ -f /usr/bin/apt ]; then
    for file in ${pkg_name_arr[@]}; do
      sudo apt-get update -y
      sudo apt-get install -y $file
    done
  fi
}

function get_glibc_version {
  local os_version=$1

  case $os_version in
    "centos:7")
      echo "2.17"
      ;;
    "centos:8")
      echo "2.28"
      ;;
    "oraclelinux:8" | "ol:8")
      echo "2.28"
      ;;
    "oraclelinux:9" | "ol:9" | "ol:9.6")
      echo "2.34"
      ;;
    "ubuntu:focal")
      echo "2.31"
      ;;
    "ubuntu:jammy" | "ubuntu:noble")
      echo "2.35"
      ;;
    "debian:bullseye")
      echo "2.31"
      ;;
    "debian:bookworm")
      echo "2.35"
      ;;
    *)
      echo "Unknown OS version"
      ;;
  esac
}

function detect_platform {
  if [ -f /etc/os-release ]; then
    source /etc/os-release
    if [[ $ID == "centos" || $ID == "ol" || $ID == "oraclelinux" ]]; then
      echo "$ID:$VERSION_ID"
    elif [[ $ID == "ubuntu" || $ID == "debian" ]]; then
      echo "$ID:$VERSION_CODENAME"
    else
      # Fallback to something, probably it will not work anyway.
      echo "2.35"
    fi
  else
    # Fallback to something, probably it will not work anyway.
    echo "2.35"
  fi
}

# Function to check if percona-release is installed
check_percona_release() {
    if command -v percona-release &>/dev/null; then
        echo "percona-release is already installed."
        return 0
    else
        echo "percona-release is not installed."
        return 1
    fi
}

# Function to install percona-release on Debian-based systems
install_debian() {
    echo "Installing percona-release for Debian-based system..."
    sudo curl -O https://repo.percona.com/apt/percona-release_latest.generic_all.deb
    sudo apt install -y gnupg2 lsb-release ./percona-release_latest.generic_all.deb
}

# Function to install percona-release on RHEL-based systems
install_rhel() {
    echo "Installing percona-release for RHEL-based system..."
    sudo yum install -y https://repo.percona.com/yum/percona-release-latest.noarch.rpm
}

platform=$(detect_platform)
glibc_version=$(get_glibc_version "$platform")
echo "The required glibc version for $platform is $glibc_version"

if ! check_percona_release; then
    if [ -f /etc/debian_version ]; then
        # Debian-based system
        install_debian
    elif [ -f /etc/redhat-release ] || [ -f /etc/centos-release ]; then
        # RHEL-based system
        install_rhel
    else
        echo "Unsupported operating system."
        exit 1
    fi
else
    echo "No installation needed."
fi

WORKDIR_ABS=$(cd ${1:-./build/proxysql}; pwd -P)
rm -rf ${WORKDIR_ABS}/WORKDIR ${WORKDIR_ABS}/PROXY_ADMIN
mkdir -p ${WORKDIR_ABS}/PROXY_ADMIN ${WORKDIR_ABS}/WORKDIR/proxysql-2.0/usr/bin ${WORKDIR_ABS}/WORKDIR/proxysql-2.0/etc

if [ -f /usr/bin/apt ]; then
  # In Linux distributions that rely on dpkg, the packages wget, gnupg2, curl and lsb-release are already installed. However, these packages may be missing from Docker base images. In this case, install them manually before running dpkg
  install_package wget gnupg2 lsb-release curl
fi

# Installing proxysql 2.0.latest package
enable_repo proxysql testing
install_package proxysql2

if [[ "${PXC_VERSION}" == "PXC84" ]]; then
  # Fetch PXC versions
  LATEST_VERSION_84=$(git ls-remote --refs --sort='version:refname' --tags https://github.com/percona/percona-xtradb-cluster | \
      grep 'Percona-XtraDB-Cluster-8.4' | tail -n1 | cut -d '/' -f3 | cut -d '-' -f4)
  VERSION_SUFFIX_84=$(git ls-remote --refs --sort='version:refname' --tags https://github.com/percona/percona-xtradb-cluster | \
      grep 'Percona-XtraDB-Cluster-8.4' | tail -n1 | cut -d '/' -f3 | cut -d '-' -f5)

  # Downloading PXC-8.4 tarball package
  sudo wget -q -O ${WORKDIR_ABS}/WORKDIR/Percona-XtraDB-Cluster_${LATEST_VERSION_84}_Linux.x86_64.glibc${glibc_version}-minimal.tar.gz\
      http://downloads.percona.com/downloads/Percona-XtraDB-Cluster-84/Percona-XtraDB-Cluster-${LATEST_VERSION_84}/binary/tarball/Percona-XtraDB-Cluster_${LATEST_VERSION_84}-${VERSION_SUFFIX_84}_Linux.x86_64.glibc${glibc_version}-minimal.tar.gz

  # Installing PXC-8.4 client package
  enable_repo pxc-84-lts release
  install_package percona-xtradb-cluster-client
elif [[ "${PXC_VERSION}" == "PXC80" ]]; then
  # Fetch PXC versions
  LATEST_VERSION_80=$(git ls-remote --refs --sort='version:refname' --tags https://github.com/percona/percona-xtradb-cluster | \
      grep 'Percona-XtraDB-Cluster-8.0' | tail -n1 | cut -d '/' -f3 | cut -d '-' -f4)
  VERSION_SUFFIX_80=$(git ls-remote --refs --sort='version:refname' --tags https://github.com/percona/percona-xtradb-cluster | \
      grep 'Percona-XtraDB-Cluster-8.0' | tail -n1 | cut -d '/' -f3 | cut -d '-' -f5)

  # Downloading PXC-8.0 tarball package
  sudo wget -q -O ${WORKDIR_ABS}/WORKDIR/Percona-XtraDB-Cluster_${LATEST_VERSION_80}_Linux.x86_64.glibc${glibc_version}-minimal.tar.gz \
      http://downloads.percona.com/downloads/Percona-XtraDB-Cluster-80/Percona-XtraDB-Cluster-${LATEST_VERSION_80}/binary/tarball/Percona-XtraDB-Cluster_${LATEST_VERSION_80}-${VERSION_SUFFIX_80}_Linux.x86_64.glibc${glibc_version}-minimal.tar.gz

  # Installing PXC-8.0 client package
  enable_repo pxc-80 release
  install_package percona-xtradb-cluster-client
elif [[ "${PXC_VERSION}" == "PXC57" ]]; then

  # Downloading PXC-5.7 tarball package
  sudo wget -q -O ${WORKDIR_ABS}/WORKDIR/Percona-XtraDB-Cluster-5.7.44-rel48-65.1.Linux.x86_64.glibc2.17-minimal.tar.gz  https://downloads.percona.com/downloads/Percona-XtraDB-Cluster-57/Percona-XtraDB-Cluster-5.7.44/binary/tarball/Percona-XtraDB-Cluster-5.7.44-rel48-65.1.Linux.x86_64.glibc2.17-minimal.tar.gz

  # Installing PXC-5.7 client
  enable_repo pxc-57 release
  install_package percona-xtradb-cluster-client-5.7

  # Installing PXB-2.4 (only required in case of PXC-5.7)
  enable_repo pxb-24 release
  install_package percona-xtrabackup-24
fi

pushd ${WORKDIR_ABS}/WORKDIR
unset PROXY_TAR_FILENAME
COPY_TIMEOUT=60

for X in $(seq 0 $COPY_TIMEOUT); do
  PROXY_TAR_FILENAME=$(ls -1 $WORKDIR_ABS/ | grep -E "proxysql.*.glibc.*.tar.gz" || ls -1 $WORKDIR_ABS/ | grep -E "proxysql-${BRANCH}.tar.gz")
  if [ -f $WORKDIR_ABS/$PROXY_TAR_FILENAME ]; then
    sudo tar -xzf $WORKDIR_ABS/$PROXY_TAR_FILENAME -C ${WORKDIR_ABS}/PROXY_ADMIN
    break;
  else
    echo "Waiting for file to copy"
  fi

  if [ $X -eq $COPY_TIMEOUT ]; then
    echo "Timout exceeded. Failed to copy proxysql tarball within time limit"
    exit 1
  fi
  sleep 1
done

for file in proxysql-admin proxysql-admin-common proxysql-login-file proxysql-common percona-scheduler-admin proxysql; do
  sudo ln -s $WORKDIR_ABS/PROXY_ADMIN/proxysql*/usr/bin/$file ${WORKDIR_ABS}/WORKDIR/$file
done;
sudo ln -s $WORKDIR_ABS/PROXY_ADMIN/proxysql*/etc/proxysql-admin.cnf ${WORKDIR_ABS}/WORKDIR/proxysql-2.0/etc/proxysql-admin.cnf
sudo ln -s $WORKDIR_ABS/PROXY_ADMIN/proxysql*/usr/bin/pxc_scheduler_handler ${WORKDIR_ABS}/WORKDIR/pxc_scheduler_handler
sudo ln -s $WORKDIR_ABS/PROXY_ADMIN/proxysql*/etc/config.toml ${WORKDIR_ABS}/WORKDIR/proxysql-2.0/etc/config.toml
sudo ln -s $WORKDIR_ABS/PROXY_ADMIN/proxysql*/tests/testsuite.toml ${WORKDIR_ABS}/WORKDIR/testsuite.toml
sudo ln -s $WORKDIR_ABS/PROXY_ADMIN/proxysql*/usr/bin/proxysql ${WORKDIR_ABS}/WORKDIR/proxysql-2.0/usr/bin/proxysql
status=0

# Running ProxySQL QA script
sudo cp /etc/hosts ${WORKDIR_ABS}/hosts.new
sudo sed -i 's/::1*.*localhost /::1 /' ${WORKDIR_ABS}/hosts.new
sudo cp -f ${WORKDIR_ABS}/hosts.new /etc/hosts

sudo sed -i 's/wsrep_sst_method=rsync/wsrep_sst_method=xtrabackup-v2/g' $WORKDIR_ABS/PROXY_ADMIN/proxysql*/tests/proxysql-admin-testsuite.sh
sudo bash $WORKDIR_ABS/PROXY_ADMIN/proxysql*/tests/proxysql-admin-testsuite.sh \
$WORKDIR_ABS/WORKDIR | tee $WORKDIR_ABS/WORKDIR/proxysql_qa.output || status=$?
process_proxysql_output PROXYSQL "$WORKDIR_ABS/WORKDIR/proxysql_qa.output" "${WORKDIR_ABS}/WORKDIR/junit.xml"
popd

exit $status
