#!/bin/bash

#  possible vars:
#      GIT_REPO
#      BRANCH

set -o errexit
set -o xtrace

ROOT_DIR=$(cd $(dirname $0)/..; pwd -P)/sources

if [ ! -d "${ROOT_DIR}" ]; then
    BRANCH_CMD=""
    if [ -n "${BRANCH}" ]; then
        BRANCH_CMD="-b ${BRANCH}"
    fi
    git clone --depth=1 "${BRANCH_CMD}" "${GIT_REPO:-https://github.com/percona/percona-xtrabackup}" "${ROOT_DIR}"
fi

pushd $ROOT_DIR

git submodule deinit -f . || true
git submodule init
git submodule update
popd
