package orphanedResources

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"regexp"
	"strings"

	"google.golang.org/api/compute/v1"
)

// gkeHashNamePattern matches names generated by GKE for Service-type
// LoadBalancer resources: literal 'a' followed by 31 hex characters
// (32-character total). We restrict the address sweep to this pattern so
// manually-created addresses (e.g. rancher-ip) are never touched.
var gkeHashNamePattern = regexp.MustCompile(`^a[0-9a-f]{31}$`)

func CleanOrphanedResources(w http.ResponseWriter, r *http.Request) {

	ctx := context.Background()
	computeService, err := compute.NewService(ctx)
	if err != nil {
		log.Fatal("Error: create service", err)
	}

	project := os.Getenv("GCP_DEV_PROJECT")
	targetPoolAggregatedList, err := computeService.TargetPools.AggregatedList(project).Do()

	if err != nil {
		log.Fatal("Error: get targetPoolAggregatedList", err)
	}

	toDelete := false
	for _, targetPoolList := range targetPoolAggregatedList.Items {
		for _, targetPoolItem := range targetPoolList.TargetPools {
			region := strings.Split(targetPoolItem.Region, "/")[8]

			if len(targetPoolItem.Instances) > 0 {
				instanceName := strings.Split(targetPoolItem.Instances[0], "/")[10]
				zone := strings.Split(targetPoolItem.Instances[0], "/")[8]
				_, err := computeService.Instances.Get(project, zone, instanceName).Context(ctx).Do()
				if err != nil && strings.Contains(err.Error(), "404") {
					toDelete = true
				}
			}

			if len(targetPoolItem.Instances) == 0 || toDelete == true {

				// Firewall-rule deleting
				firewallRuleId := fmt.Sprintf("k8s-fw-%s", targetPoolItem.Name)

				respFirewall, err := computeService.Firewalls.Delete(project, firewallRuleId).Context(ctx).Do()
				if err != nil {
					log.Printf("We can't delete firewallRuleId: %v", err)
				} else {
					log.Printf("firewall-rule deleted: k8s-fw- %s was deleted with status %s\n", targetPoolItem.Name, respFirewall.Status)
				}

				// Forwarding-rule deleting
				respFWRule, err := computeService.ForwardingRules.Delete(project, region, targetPoolItem.Name).Context(ctx).Do()
				if err != nil {
					log.Printf("We can't delete Forwarding-rule: %v", err)
				} else {
					log.Printf("forwarding-rule deleted: %s was deleted with status %s\n", targetPoolItem.Name, respFWRule.Status)
				}

				// Address deleting
				respAdd, err := computeService.Addresses.Delete(project, region, targetPoolItem.Name).Context(ctx).Do()
				if err != nil {
					log.Printf("We can't delete Address: %v", err)
				} else {
					log.Printf("address deleted: %s was deleted with status %s\n", targetPoolItem.Name, respAdd.Status)
				}

				// Target pool deleting
				respTP, err := computeService.TargetPools.Delete(project, region, targetPoolItem.Name).Context(ctx).Do()
				if err != nil {
					log.Printf("We can't delete target pool: %v", err)
				} else {
					log.Printf("Target-pool deleted: %s was deleted with status %s\n", targetPoolItem.Name, respTP.Status)
				}
			}
		}
	}

	// --- Pass 2: sweep orphaned RESERVED addresses whose TargetPool no longer
	// exists. Pass 1 only touches addresses that share a name with a live
	// TargetPool, so hash-named GKE addresses left behind by prior teardowns
	// stay reserved and eventually exhaust the STATIC_ADDRESSES quota.
	addressAggregatedList, err := computeService.Addresses.AggregatedList(project).Do()
	if err != nil {
		log.Printf("Error: get addressAggregatedList: %v", err)
		return
	}

	for _, addressScoped := range addressAggregatedList.Items {
		for _, addr := range addressScoped.Addresses {
			if addr.Status != "RESERVED" {
				continue
			}
			if len(addr.Users) > 0 {
				continue
			}
			if !gkeHashNamePattern.MatchString(addr.Name) {
				continue
			}
			if addr.Region == "" {
				continue
			}

			region := addr.Region[strings.LastIndex(addr.Region, "/")+1:]

			respAdd, err := computeService.Addresses.Delete(project, region, addr.Name).Context(ctx).Do()
			if err != nil {
				log.Printf("Orphan address sweep: cannot delete %s in %s: %v", addr.Name, region, err)
				continue
			}
			log.Printf("Orphan address sweep: deleted %s in %s with status %s\n", addr.Name, region, respAdd.Status)
		}
	}
}
