---
# OpenShift Security Context Constraints for PMM HA workloads
# Allows PMM service accounts to run with anyuid
#
# Usage:
#   oc apply -f pmm/v3/resources/pmm-anyuid-scc.yaml
#
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: pmm-anyuid
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - MKNOD
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:pmm:default
  - system:serviceaccount:pmm:pmm-service-account
  - system:serviceaccount:pmm:pmm-ha-haproxy
  - system:serviceaccount:pmm:pmm-ha-pg-db
  - system:serviceaccount:pmm:pmm-ha-pmmdb
  - system:serviceaccount:pmm:pmm-ha-vmagent
  - system:serviceaccount:pmm:pmm-ha-secret-generator
  - system:serviceaccount:pmm:pmm-ha-dependencies-altinity-clickhouse-operator
  - system:serviceaccount:pmm:pmm-ha-dependencies-pg-operator
  - system:serviceaccount:pmm:pmm-ha-dependencies-victoria-metrics-operator
volumes:
  - configMap
  - csi
  - downwardAPI
  - emptyDir
  - ephemeral
  - persistentVolumeClaim
  - projected
  - secret
