#!/bin/bash

#  possible vars:
#      GIT_REPO
#      BRANCH
#      PXC_GALERA_REPO
#      PXC_GALERA_BRANCH
#      PXB80_REPO
#      PXB80_BRANCH
#      PXB24_REPO
#      PXB24_BRANCH
#      WSREP_LIB_REPO
#      WSREP_LIB_BRANCH

set -o errexit
set -o xtrace

SOURCE_NAME=${1:-'ALL'}

ROOT_DIR=$(cd $(dirname $0)/..; pwd -P)/sources

if [ ! -d "${ROOT_DIR}" ]; then
    mkdir -p ${ROOT_DIR}
fi

# ==================== PXC ====================

if [ "$SOURCE_NAME" == 'PXC80' -o "$SOURCE_NAME" == 'ALL' ]; then
    PXC_ROOT_DIR="${ROOT_DIR}/pxc"

    sudo rm -rf ${PXC_ROOT_DIR}

    git clone "${GIT_REPO:-https://github.com/percona/percona-xtradb-cluster}" "${PXC_ROOT_DIR}"

    pushd $PXC_ROOT_DIR
        if [ -n "${GIT_REPO}" ]; then
            git remote set-url origin "${GIT_REPO}"
            git fetch --all
        fi
         
        git reset --hard
        git clean -xdf

        mkdir ./target

        if [ -n "${BRANCH}" ]; then
            git checkout "${BRANCH}"
        fi
        if [ -n "${GIT_REPO}" -a -n "${BRANCH}" ]; then
            git pull origin ${BRANCH}
        fi

        if [ -n "${PXC_GALERA_REPO}" ]; then
            git config -f .gitmodules submodule.percona-xtradb-cluster-galera.url "${PXC_GALERA_REPO}"
        fi
        if [ -n "${PXC_GALERA_BRANCH}" ]; then
            git config -f .gitmodules submodule.percona-xtradb-cluster-galera.branch "${PXC_GALERA_BRANCH}"
        fi

        if [ -n "${WSREP_LIB_REPO}" ]; then
            git config -f .gitmodules submodule.wsrep-lib.url "${WSREP_LIB_REPO}"
        fi
        if [ -n "${WSREP_LIB_BRANCH}" ]; then
            git config -f .gitmodules submodule.wsrep-lib.branch "${WSREP_LIB_BRANCH}"
        fi

        git submodule update --init

        if [ -n "${PXC_GALERA_REPO}" -o -n "${PXC_GALERA_BRANCH}" ]; then
            git submodule update --init --remote ./percona-xtradb-cluster-galera
        fi

        if [ -n "${WSREP_LIB_REPO}" -o -n "${WSREP_LIB_BRANCH}" ]; then
            git submodule update --init --remote ./wsrep-lib
        fi

        pushd wsrep-lib
            git submodule deinit -f . || true
            git submodule init
            git submodule update
        popd

        pushd percona-xtradb-cluster-galera
            if [ -n "${WSREP_LIB_REPO}" ]; then
                 git config -f .gitmodules submodule.wsrep-lib.url "${WSREP_LIB_REPO}"
            fi
            if [ -n "${WSREP_LIB_BRANCH}" ]; then
                git config -f .gitmodules submodule.wsrep-lib.branch "${WSREP_LIB_BRANCH}"
            fi

            git submodule deinit -f . || true
            git submodule init
            git submodule update
        popd

    popd
fi


# ==================== PXB80 ====================

if [ "$SOURCE_NAME" == 'PXB80' -o "$SOURCE_NAME" == 'ALL' ]; then
    PXB80_ROOT_DIR="${ROOT_DIR}/pxb80"

    sudo rm -rf ${PXB80_ROOT_DIR}

    git clone "${PXB80_REPO:-https://github.com/percona/percona-xtrabackup}" "${PXB80_ROOT_DIR}"

    pushd $PXB80_ROOT_DIR
        if [ -n "${PXB80_REPO}" ]; then
            git remote set-url origin "${PXB80_REPO}"
            git fetch --all
        fi

        git reset --hard
        git clean -xdf

        if [[ ${PXB80_LATEST} == "true" ]]; then
            git checkout 8.0
            unset PXB80_BRANCH && PXB80_BRANCH="$(git describe --tags --abbrev=0)"
        fi
        if [ -n "${PXB80_BRANCH}" ]; then
            git checkout "${PXB80_BRANCH}" -b "tag-${PXB80_BRANCH}"
        fi
        if [ -n "${PXB80_REPO}" -a -n "${PXB80_BRANCH}" ]; then
            git pull origin ${PXB80_BRANCH}
        fi
     popd
fi

# ==================== PXB24 ====================

if [ "$SOURCE_NAME" == 'PXB24' -o "$SOURCE_NAME" == 'ALL' ]; then
    PXB24_ROOT_DIR="${ROOT_DIR}/pxb24"
 
    sudo rm -rf ${PXB24_ROOT_DIR}

    git clone "${PXB24_REPO:-https://github.com/percona/percona-xtrabackup}" "${PXB24_ROOT_DIR}"

    pushd $PXB24_ROOT_DIR
        if [ -n "${PXB24_REPO}" ]; then
            git remote set-url origin "${PXB24_REPO}"
            git fetch --all
        fi

        git reset --hard
        git clean -xdf

        if [ -n "${PXB24_BRANCH}" ]; then
            git checkout "${PXB24_BRANCH}" -b "tag-${PXB24_BRANCH}"
        fi
        if [ -n "${PXB24_REPO}" -a -n "${PXB24_BRANCH}" ]; then
            git pull origin ${PXB24_BRANCH}
        fi
    popd
fi
