#!/bin/bash

#  possible vars:
#      PXC57_REPO
#      PXC57_BRANCH
#      PXB24_REPO
#      PXB24_BRANCH

set -o errexit
set -o xtrace

SOURCE_NAME=${1:-'ALL'}

ROOT_DIR=$(cd $(dirname $0)/..; pwd -P)/sources

if [ ! -d "${ROOT_DIR}" ]; then
    mkdir -p ${ROOT_DIR}
fi

# ==================== PXC ====================

if [ "$SOURCE_NAME" == 'PXC57' -o "$SOURCE_NAME" == 'ALL' ]; then
    PXC_ROOT_DIR="${ROOT_DIR}/pxc57"

    sudo rm -rf ${PXC_ROOT_DIR}

    git clone "${PXC57_REPO:-https://github.com/percona/percona-xtradb-cluster}" "${PXC_ROOT_DIR}"

    pushd $PXC_ROOT_DIR
        if [ -n "${PXC57_REPO}" ]; then
            git remote set-url origin "${PXC57_REPO}"
            git fetch --all
        fi
         
        git reset --hard
        git clean -xdf

        mkdir ./target

        if [[ ${USE_PR} == "true" ]]; then
            git fetch origin pull/${PXC57_BRANCH}/head:pr-${PXC57_BRANCH}
        fi
        if [ -n "${PXC57_BRANCH}" ]; then
            if [[ ${USE_PR} == "true" ]]; then
                git checkout pr-${PXC57_BRANCH}
            else      
                git checkout "${PXC57_BRANCH}"
            fi
        fi
        if [ -n "${PXC57_REPO}" -a -n "${PXC57_BRANCH}" ]; then
            if [[ ${USE_PR} == "true" ]]; then
                git pull origin pull/${PXC57_BRANCH}/head:pr-${PXC57_BRANCH}
            else
                git pull origin ${PXC57_BRANCH}
            fi
        fi
		
		rm -rf percona-xtradb-cluster-galera || true
		git submodule deinit -f . || true
		git submodule init
		git submodule update

		cd percona-xtradb-cluster-galera
		git submodule deinit -f . || true
		git submodule init
		git submodule update

    popd
fi


# ==================== PXB24 ====================

if [ "$SOURCE_NAME" == 'PXB24' -o "$SOURCE_NAME" == 'ALL' ]; then
    PXB24_ROOT_DIR="${ROOT_DIR}/pxb24"
 
    sudo rm -rf ${PXB24_ROOT_DIR}

    git clone "${PXB24_REPO:-https://github.com/percona/percona-xtrabackup}" "${PXB24_ROOT_DIR}"

    pushd $PXB24_ROOT_DIR
        if [ -n "${PXB24_REPO}" ]; then
            git remote set-url origin "${PXB24_REPO}"
            git fetch --all
        fi

        git reset --hard
        git clean -xdf

        if [ -n "${PXB24_BRANCH}" ]; then
            git checkout "${PXB24_BRANCH}" -b "tag-${PXB24_BRANCH}"
        fi
        if [ -n "${PXB24_REPO}" -a -n "${PXB24_BRANCH}" ]; then
            git pull origin ${PXB24_BRANCH}
        fi
    popd
fi