#!/bin/bash
#
# Execute this tool to test binary releases
#
#  possible jenkins vars:
#      CMAKE_BUILD_TYPE = (RelWithDebInfo Debug)
#      MTR_ARGS
#      MTR_REPEAT
#      GALERA_PARALLEL_RUN
#      MTR_SUITES
#      MTR_STANDALONE_TESTS
#      MTR_STANDALONE_TESTS_PARALLEL
#      DOCKER_OS
#      ANALYZER_OPTS = (-DWITH_ASAN=ON -DWITH_ASAN_SCOPE=ON -DWITH_MSAN=ON -DWITH_UBSAN=ON -DWITH_VALGRIND=ON)
#      CI_FS_MTR
#      WORKER_NO
#      PXB_PREV_LTS_TARGET_DIR
#      PXB_A_TARGET_DIR
#      PXB_B_TARGET_DIR

set -o errexit
set -o xtrace

EXECUTION_GROUP_NO=0
function executeSuites() {
    local suites=$1
    local extraOptions=$2
    local parallel=$3

    if [[ -z ${suites} ]]; then
        return
    fi

    # 'worker' holds the name of the file with results.
    # As we call this function several times, avoid overriding the file.
    EXECUTION_GROUP_NO=$((EXECUTION_GROUP_NO+1))
    local worker="WORKER_${WORKER_NO}_${EXECUTION_GROUP_NO}"

    echo "Executing suites $suites"

    df -h
    du /dev/shm
    mount
    ls -la /dev/shm
    cat /proc/meminfo

    MTR_ARGS_NORMAL=${MTR_ARGS}

    MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
        --parallel=${parallel} \
        --result-file \
        --suite=$suites \
        --suite-timeout=9999 \
        --testcase-timeout=${TESTCASE_TIMEOUT} \
        --force --mysqld-env="LD_PRELOAD=${MYSQLD_ENV}" \
        --max-test-fail=0 \
        ${MTR_ARGS_NORMAL} \
        ${extraOptions} \
        --junit-output=${WORKDIR_ABS}/junit_${worker}.xml \
        --junit-package="${DOCKER_OS}.${CMAKE_BUILD_TYPE}.${worker}"  | tee -a ${LOG_FILE} || true

    ln -s $PWD/var $PWD/var_${worker}
    which rsync
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_${worker} $PWD/mtr_var

    killall -9 mysqld || true
    rm -rf $PWD/var_${worker}

    df -h
    du -sh /dev/shm

    end=`date +%s`
    runtime=$((end-start))
    echo KH,SUITES,${suites},time,$runtime
}




echo "*******************************************************"
whoami
grep -c ^processor /proc/cpuinfo
free
prlimit
#disable core generation
ulimit -c 0
ulimit -a
echo "*******************************************************"


# PXC >>>
WORKDIR_ABS=$(cd ${1:-./build/pxc}; pwd -P)
rm -fr ${WORKDIR_ABS}/PXC
mkdir -p ${WORKDIR_ABS}/PXC/sql
tar -C ${WORKDIR_ABS}/PXC --strip-components=1 -zxpf $(ls $WORKDIR_ABS/*.tar.gz | head -1)

# this is needed for unit tests execution
mv ${WORKDIR_ABS}/PXC/runtime_output_directory ${WORKDIR_ABS}/runtime_output_directory
mv ${WORKDIR_ABS}/PXC/plugin_output_directory ${WORKDIR_ABS}/plugin_output_directory
mv ${WORKDIR_ABS}/PXC/library_output_directory ${WORKDIR_ABS}/library_output_directory
# PXC <<<

# PXB >>>
function preparePXB() {
    local target_dir=$1
    local tarball_file=$2

    if [[ -n "${target_dir}" ]]; then
        local tmp_workdir=$WORKDIR_ABS/pxb_tmp
        mkdir -p ${tmp_workdir}/target
        tar -xzf ${WORKDIR_ABS}/${tarball_file} --exclude='man' --exclude='*-test' -C ${tmp_workdir}/target
        mv ${tmp_workdir}/target/$(ls ${tmp_workdir}/target | grep percona-xtrabackup-) ${tmp_workdir}/target/${target_dir}
        mkdir -p ${WORKDIR_ABS}/PXC/bin/pxc_extra/${target_dir}
        cp -v -r ${tmp_workdir}/target/${target_dir}/{bin,lib} ${WORKDIR_ABS}/PXC/bin/pxc_extra/${target_dir}
        rm -rf ${tmp_workdir}
    fi
}

echo "PXB_PREV_LTS_TARGET_DIR: ${PXB_PREV_LTS_TARGET_DIR}"
preparePXB  ${PXB_PREV_LTS_TARGET_DIR} "pxb_prev_LTS/pxb_prev_LTS.tar.gz"

echo "PXB_A_TARGET_DIR: ${PXB_A_TARGET_DIR}"
preparePXB ${PXB_A_TARGET_DIR} "pxb_A/pxb_A.tar.gz"

echo "PXB_B_TARGET_DIR: ${PXB_B_TARGET_DIR}"
preparePXB ${PXB_B_TARGET_DIR} "pxb_B/pxb_B.tar.gz"

# PXB <<<

#
# Galera
export WSREP_PROVIDER=${WORKDIR_ABS}/PXC/lib/libgalera_smm.so

LOG_FILE=${WORKDIR_ABS}/mtr-test.log

cd ${WORKDIR_ABS}/PXC/mysql-test
TESTCASE_TIMEOUT=10
# CentOS 7
if [[ -f /opt/rh/devtoolset-8/enable ]]; then
    source /opt/rh/devtoolset-8/enable
fi

#
# Determine what we've got in the environent
JEMALLOC=$(find /lib* /usr/lib* /usr/local/lib* -type f -name 'libjemalloc.so*' | head -n1)
EATMYDATA=$(find /lib* /usr/lib* /usr/local/lib* -type f -name '*eatmyda*.so*' | head -n1)
OPENSSL_HEADER="/usr/include/openssl/opensslv.h"
OPENSSL_VER=$(grep -o 'define SHLIB_VERSION_NUMBER .*$' ${OPENSSL_HEADER} | awk -F'"' '{print $(NF-1)}' | sed -e 's:[a-z]::g')

if [[ -z "${EATMYDATA}" ]]; then
  echo "No libeatmydata.so lib found"
  exit 1
fi

if [[ -z "${JEMALLOC}" ]]; then
  echo "No jemalloc lib found"
  exit 1
fi

if [[ -n "${MTR_REPEAT}" ]]; then
  MTR_ARGS+=" --repeat=${MTR_REPEAT}"
fi

if [[ "${MTR_ARGS}" == *"--suite=max_parts"* ]]; then
    TESTCASE_TIMEOUT=$((TESTCASE_TIMEOUT * 6))
fi

PARALLEL=$(grep -c ^processor /proc/cpuinfo)
galera_extra_options=
#
# asan/valgrind
if [[ "${ANALYZER_OPTS}" == *WITH_VALGRIND=ON* ]]; then
  MTR_ARGS+=" --valgrind --valgrind-clients --valgrind-option=--leak-check=full --valgrind-option=--show-leak-kinds=all"
  galera_extra_options=" --only-combinations=enc_off"
  [[ ${OPENSSL_VER} < '1.0.2' ]] && export OPENSSL_ia32cap=~0x200000000000000
  # No, MTR runner already has --testcase-timeout * 10
  # TESTCASE_TIMEOUT=$((TESTCASE_TIMEOUT * 6))
  if [[ ${PARALLEL} -gt 1 ]]; then
    PARALLEL=$((PARALLEL/3))
  fi
fi

# hack for too big instances ;)
if [[ ${PARALLEL} -gt 10 ]]; then
  echo "Limit parallel ${PARALLEL} -> 10"
  PARALLEL=10
fi

if [[ "${ANALYZER_OPTS}" == *WITH_*SAN*=ON* ]]; then
    MTR_ARGS+=" --sanitize"
fi

if [[ "${ANALYZER_OPTS}" == *WITH_ASAN=ON* ]]; then
  # detect_odr_violation:
  # If >=2, detect violation of One-Definition-Rule (ODR);
  # If ==1, detect ODR-violation only if the two variables have different sizes
  export ASAN_OPTIONS=allocator_may_return_null=true:detect_odr_violation=1
  # trying to find the proper library
  MYSQLD=$(find ${WORKDIR_ABS}/PXC/bin -name mysqld)
  LIBASAN=$(ldd ${MYSQLD} | grep libasan | awk '{print $3}')
  ADD_TO_LD_PRELOAD="${LIBASAN}:"
fi


#
# execute big tests in separate run
BIG_TEST=0
ONLY_BIG_TEST=0
big_test_extra_option=
only_big_test_extra_option=
if [[ $MTR_ARGS == *"--big-test"* ]]; then
    BIG_TEST=1
    big_test_extra_option="--big-test"
fi
if [[ $MTR_ARGS == *"--only-big-test"* ]]; then
    ONLY_BIG_TEST=1
    BIG_TEST=1
    only_big_test_extra_option="--only-big-test"
fi
MTR_ARGS=${MTR_ARGS//"--big-test"/""}
MTR_ARGS=${MTR_ARGS//"--only-big-test"/""}

#
# unit tests
UNIT_TESTS=0
if [[ $MTR_ARGS == *"--unit-tests-report"* ]]; then
    UNIT_TESTS=1
fi
MTR_ARGS=${MTR_ARGS//"--unit-tests-report"/""}


status=0

#
# adjustments for Valgrind
if [[ "${ANALYZER_OPTS}" == *WITH_VALGRIND=ON* ]]; then
    MYSQLD_ENV=--mysqld-env=\"LD_PRELOAD=${ADD_TO_LD_PRELOAD:-}${EATMYDATA}\"
else
    MYSQLD_ENV=--mysqld-env=\"LD_PRELOAD=${ADD_TO_LD_PRELOAD:-}${JEMALLOC}:${EATMYDATA}\"
fi

#
# This is a hack. SST script fails with LD_LIBRARY=libasan.so. It has to be specified if we are using
# jemalloc/eatmydata.
# Wrap SST script with empty LD_PRELOAD env
if [[ "${ANALYZER_OPTS}" == *WITH_ASAN=ON* ]]; then
    pushd ${WORKDIR_ABS}/PXC/bin
    mv wsrep_sst_xtrabackup-v2 wsrep_sst_xtrabackup-v2.bin

    cat << EOF > wsrep_sst_xtrabackup-v2
#!/bin/bash
export LD_PRELOAD=
${WORKDIR_ABS}/PXC/bin/wsrep_sst_xtrabackup-v2.bin "\$@";
EOF

    chmod a+rx wsrep_sst_xtrabackup-v2
    popd
fi

if [[ -f /etc/redhat-release ]]; then
    sudo yum install -y net-tools netcat
else
    sudo apt update
    sudo apt install -y net-tools netcat-openbsd
fi
ifconfig

mkdir mtr_var

#
# >>>> execute all unit tests at the beginning with main.1st
if [[ $UNIT_TESTS == "1" ]]; then
    tests="main.1st"
    suiteNoSlash="UNIT_TESTS"
    echo "Executing unit tests with $tests"

        df -h
        du /dev/shm
        mount
        ls -la /dev/shm
        cat /proc/meminfo
    start=`date +%s`

    env MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
        --parallel=${PARALLEL} \
        --result-file \
        --unit-tests-report \
        ${tests} \
        ${MTR_ARGS} \
        --force \
        --max-test-fail=0 \
        --junit-output=${WORKDIR_ABS}/junit_${suiteNoSlash}.xml \
        --junit-package="${DOCKER_OS}.${CMAKE_BUILD_TYPE}.${suiteNoSlash}" || true

    ln -s $PWD/var $PWD/var_${suiteNoSlash}
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_${suiteNoSlash} $PWD/mtr_var

    killall -9 mysqld || true
    rm -rf $PWD/var_${suiteNoSlash}

    df -h
    du -sh /dev/shm

    end=`date +%s`
    runtime=$((end-start))
    echo KH,UNIT_TESTS,${tests},time,$runtime
        fi

#
# Execute MTR tests
suitesNormal=
suitesBig=
suitesSmall=
suitesReplicationNormal=
suitesReplicationBig=
suitesReplicationSmall=
suitesGaleraNormal=
suitesGaleraBig=
suitesGaleraSmall=

# collect suites
ARRAY_MTR_SUITES=($(echo $MTR_SUITES | sed 's/,/ /g'))
for suite in "${ARRAY_MTR_SUITES[@]}"; do
    only_big_tests_this=0
    only_small_tests_this=0

    # suite may be in form:
    # main
    # main|big
    # main|nobig
    arrSuite=(${suite//|/ })
    suite=${arrSuite[0]}
    big=${arrSuite[1]}

    if [[ "${big}" == "big" ]]; then
        if [[ $BIG_TEST == 0 ]]; then
            continue
        fi
        only_big_tests_this=1
        # only big
    elif [[ "${big}" == "nobig" ]]; then
        # only nobig
        if [[ $ONLY_BIG_TEST == 1 ]]; then
            continue
        fi
        only_small_tests_this=1
    else
        # normal (big + nobig)
        only_big_tests_this=0
        only_small_tests_this=0
    fi

    if [[ "${ANALYZER_OPTS}" == *WITH_VALGRIND=ON* ]]; then
      if [[ "$suite" == "galera_encryption" ]]; then
        echo "Skipping $suite suite for Valgrind build"
        continue
      fi
    fi

    if [[ $only_big_tests_this == "1" ]]; then
        if [[ "$suite" == *"galera"* || "${suite}" == "wsrep" ]]; then
            suitesGaleraBig+="$suite,"
        elif [[ "${suite}" == "group_replication" || "${suite}" == *rpl* ]]; then
            suitesReplicationBig+="$suite,"
        else
            suitesBig+="$suite,"
    fi
    elif [[ $only_small_tests_this == "1" ]]; then
        if [[ "$suite" == *"galera"* || "${suite}" == "wsrep" ]]; then
            suitesGaleraSmall+="$suite,"
        elif [[ "${suite}" == "group_replication" || "${suite}" == *rpl* ]]; then
            suitesReplicationSmall+="$suite,"
        else
            suitesSmall+="$suite,"
        fi
    else
        if [[ "$suite" == *"galera"* || "${suite}" == "wsrep" ]]; then
            suitesGaleraNormal+="$suite,"
        elif [[ "${suite}" == "group_replication" || "${suite}" == *rpl* ]]; then
            suitesReplicationNormal+="$suite,"
        else
            suitesNormal+="$suite,"
        fi
    fi
done

echo "MTR normal suites: $suitesNormal"
echo "MTR big suites: $suitesBig"
echo "MTR small suites: $suitesSmall"
echo "MTR replication normal suites: $suitesReplicationNormal"
echo "MTR replication big suites: $suitesReplicationBig"
echo "MTR replication small suites: $suitesReplicationSmall"
echo "MTR galera normal suites: $suitesGaleraNormal"
echo "MTR galera big suites: $suitesGaleraBig"
echo "MTR galera small suites: $suitesGaleraSmall"

# Execute suites
start=`date +%s`

executeSuites "$suitesNormal" "${big_test_extra_option}" "${PARALLEL}"
executeSuites "$suitesBig" "--only-big-test" "${PARALLEL}"
executeSuites "$suitesSmall" "" "${PARALLEL}"

# For galera tests, force --parallel force the value via 2nd parameter
executeSuites "$suitesGaleraNormal" "${big_test_extra_option} $galera_extra_options --parallel=${GALERA_PARALLEL_RUN}" "${GALERA_PARALLEL_RUN}"
executeSuites "$suitesGaleraBig" "--only-big-test $galera_extra_options --parallel=${GALERA_PARALLEL_RUN}" "${GALERA_PARALLEL_RUN}"
executeSuites "$suitesGaleraSmall" "$galera_extra_options --parallel=${GALERA_PARALLEL_RUN}" "${GALERA_PARALLEL_RUN}"

# For replication suites, use less workers. Let's say 3 cpus per worker...
RPL_PARALLEL_RUN=$((PARALLEL/3))        
# ...but not less than GALERA_PARALLEL_RUN (to have it still configurable via Jenkins UI)
if [[ ${RPL_PARALLEL_RUN} -lt ${GALERA_PARALLEL_RUN} ]]; then
  RPL_PARALLEL_RUN=${GALERA_PARALLEL_RUN}
fi
echo "Limiting workers count for replication suites to ${RPL_PARALLEL_RUN}"
# For replication tests, force --parallel force the value via 2nd parameter
executeSuites "$suitesReplicationNormal" "${big_test_extra_option} --parallel=${RPL_PARALLEL_RUN}" "${RPL_PARALLEL_RUN}"
executeSuites "$suitesReplicationBig" "--only-big-test --parallel=${RPL_PARALLEL_RUN}" "${RPL_PARALLEL_RUN}"
executeSuites "$suitesReplicationSmall" "--parallel=${RPL_PARALLEL_RUN}" "${RPL_PARALLEL_RUN}"


#
# CI FS tests
if [[ "${CI_FS_MTR}" = 'yes' ]]; then
    echo "Running CI FS tests"
    start=`date +%s`

    # For CIFS tests we have a small disk. Limit the parallel option, even if
    # it was explicitly set in MTR_ARGS
    if [[ ${PARALLEL} -gt 10 ]]; then
    echo "Limit parallel ${PARALLEL} -> 10"
    PARALLEL=10
    fi

    # no --mem allowed if vardir specified
    MTR_ARGS=${MTR_ARGS//"--mem"/""}

    if [[ $BIG_TEST == "1" ]]; then
        MTR_ARGS+=" --big-test"
    fi

    # Collect all CI_FS tests
    CI_TESTS=$(grep --exclude="*.inc" --exclude="*.log" -rl . -e include/have_case_insensitive_file_system.inc | awk -F '/' '{print $(NF-2)"."$NF}' | sed 's/\.test//g' | sed 's/^\./main/g')
    # Requested in PS-7602
    CI_TESTS+=" information_schema.i_s_schema_definition_debug"

    # Filter out disabled tests
    # Skip lines starting with #
    # Grab until whitespace or :
    DISABLED_TESTS=$(grep -P -o collections/disabled.def -e'^\s*[^#][^:\s]*')

    set +x
    for CURRENT_TEST in $DISABLED_TESTS; do
        CI_TESTS=$(echo $CI_TESTS | sed "s/\b${CURRENT_TEST}\b//g")
    done
    set -x

    MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
        --result-file \
        --force ${MYSQLD_ENV} \
        --max-test-fail=0 \
        --suite-timeout=9999 \
        --testcase-timeout=${TESTCASE_TIMEOUT} \
        ${MTR_ARGS} \
        --tmpdir="/tmp/ps_mtr_tempdir" \
        --vardir="/tmp/ci_disk_dir/var" \
        --parallel=${PARALLEL} \
        ${CI_TESTS} \
        --junit-output=${WORKDIR_ABS}/junit_ci_fs.xml \
        --junit-package="${DOCKER_OS}.${CMAKE_BUILD_TYPE}.ci_fs" | tee -a ${LOG_FILE} || true

    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' /tmp/ci_disk_dir $PWD/mtr_var

    end=`date +%s`
    runtime=$((end-start))
    echo KH,SUITE_TOTAL,CI_FS_tests,time,$runtime
fi

#
# standalone tests
if [[ -n "${MTR_STANDALONE_TESTS}" ]]; then
    echo "Running standalone tests"
    MTR_ARGS+=" --big-test"
    suiteNoSlash="standalone_tests"

    start=`date +%s`

    df -h
    du /dev/shm
    mount
    ls -la /dev/shm
    cat /proc/meminfo

    MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
        --result-file \
        --force ${MYSQLD_ENV} \
        --max-test-fail=0 \
        --suite-timeout=9999 --parallel=${MTR_STANDALONE_TESTS_PARALLEL} \
        --port-group-size=20 \
        --testcase-timeout=${TESTCASE_TIMEOUT} \
        ${MTR_ARGS} \
        --junit-output=${WORKDIR_ABS}/junit_${suiteNoSlash}.xml \
        --junit-package="${DOCKER_OS}.${CMAKE_BUILD_TYPE}.${suiteNoSlash}" ${MTR_STANDALONE_TESTS} | tee -a ${LOG_FILE} || true

    ln -s $PWD/var $PWD/var_${suiteNoSlash}
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_${suiteNoSlash} $PWD/mtr_var

    killall -9 mysqld || true
    rm -rf $PWD/var_${suiteNoSlash}

    df -h
    du -sh /dev/shm

    end=`date +%s`
    runtime=$((end-start))
    echo KH,SUITE_TOTAL,${suite},time,$runtime
fi

# Convert Latin1(ISO-8859-1) into browser readable UTF-8
for file in $(find ${WORKDIR_ABS}/ -maxdepth 1 -name "*.xml"); do
    iconv -c -t UTF-8 ${file} | tr -cd '[:print:]\n\r' > ${file}-converted
    mv ${file}-converted ${file}
done

exit $status
