#!/bin/bash
#
# Execute this tool to test binary releases
#
#  possible jenkins vars:
#      CMAKE_BUILD_TYPE = (RelWithDebInfo Debug)
#      MTR_ARGS
#      MTR_REPEAT
#      GALERA_PARALLEL_RUN
#      MTR_SUITES
#      MTR_STANDALONE_TESTS
#      MTR_STANDALONE_TESTS_PARALLEL
#      DOCKER_OS
#      ANALYZER_OPTS = (-DWITH_ASAN=ON -DWITH_ASAN_SCOPE=ON -DWITH_MSAN=ON -DWITH_UBSAN=ON -DWITH_VALGRIND=ON)
#      CI_FS_MTR
#      WORKER_NO

set -o errexit
set -o xtrace

# Execution mode. If suites should be executed one by one, or all together
EXECUTE_SUITES_ONE_BY_ONE=1


function execute() {
    local suites=$1
    local parallel=$2
    local extraOptions=$3
    local logFileSuffix=$4

    if [[ -z ${suites} ]]; then
        return
    fi

    local worker="WORKER_${WORKER_NO}_${logFileSuffix}"
    # ensure that there are not / in worker name (it can come from suites that have / in their names)
    worker=${worker//"/"/"_"}

    echo "Executing suites $suites $logFileSuffix"

    df -h
    du /dev/shm
    mount
    ls -la /dev/shm
    cat /proc/meminfo

    start=`date +%s`

    MTR_ARGS_NORMAL=${MTR_ARGS}

    MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
        --parallel=${parallel} \
        --result-file \
        --suite=$suites \
        --suite-timeout=9999 \
        --testcase-timeout=${TESTCASE_TIMEOUT} \
        --force ${MYSQLD_ENV} \
        --max-test-fail=0 \
        ${MTR_ARGS_NORMAL} \
        ${extraOptions} \
        --junit-output=${WORKDIR_ABS}/junit_${worker}.xml \
        --junit-package="${DOCKER_OS}.${CMAKE_BUILD_TYPE}.${worker}"  | tee -a ${LOG_FILE} || true

    ln -s $PWD/var $PWD/var_${worker}
    which rsync
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_${worker} $PWD/mtr_var

    killall -9 mysqld || true
    rm -rf $PWD/var_${worker}

    df -h
    du -sh /dev/shm

    end=`date +%s`
    runtime=$((end-start))
    echo KH,SUITES,${suites}-${logFileSuffix},time,$runtime
}


function executeOneSuite() {
    if [[ ${EXECUTE_SUITES_ONE_BY_ONE} == 0 ]]; then
      return
    fi

    local suite=$1
    local parallel=$2
    local extraOptions=$3
    local extraSuffix=${4:+-"$4"}

    if [[ -z ${suite} ]]; then
        return
    fi
    
    execute "${suite}" "${parallel}" "${extraOptions}" "${suite}${extraSuffix}"
}


EXECUTION_GROUP_NO=0
function executeSuites() {
    if [[ ${EXECUTE_SUITES_ONE_BY_ONE} == 1 ]]; then
      return
    fi

    local suite=$1
    local parallel=$2
    local extraOptions=$3

    if [[ -z ${suites} ]]; then
        return
    fi

    # 'worker' holds the name of the file with results.
    # As we call this function several times, avoid overriding the file.
    EXECUTION_GROUP_NO=$((EXECUTION_GROUP_NO+1))
    
    execute "${suite}" "${parallel}" "${extraOptions}" "${EXECUTION_GROUP_NO}"
}


echo "*******************************************************"
whoami
grep -c ^processor /proc/cpuinfo
free
prlimit
#disable core generation
ulimit -c 0
ulimit -a
echo "*******************************************************"


# PXC >>>
WORKDIR_ABS=$(cd ${1:-./build/pxc}; pwd -P)
rm -fr ${WORKDIR_ABS}/PXC
mkdir -p ${WORKDIR_ABS}/PXC/sql
tar -C ${WORKDIR_ABS}/PXC --strip-components=1 -zxpf $(ls $WORKDIR_ABS/*.tar.gz | head -1)

# this is needed for unit tests execution
mv ${WORKDIR_ABS}/PXC/runtime_output_directory ${WORKDIR_ABS}/runtime_output_directory
mv ${WORKDIR_ABS}/PXC/plugin_output_directory ${WORKDIR_ABS}/plugin_output_directory
mv ${WORKDIR_ABS}/PXC/library_output_directory ${WORKDIR_ABS}/library_output_directory
# PXC <<<

# PXB >>>
PXB24_WORKDIR=$WORKDIR_ABS/pxb24
PXB80_WORKDIR=$WORKDIR_ABS/pxb80

PXB24_TAR=$(ls $PXB24_WORKDIR/{percona-xtrabackup-2.*.tar.gz,pxb24.tar.gz}  | awk -F'/' '{print $NF}')
PXB80_TAR=$(ls $PXB80_WORKDIR/{percona-xtrabackup-8.*.tar.gz,pxb80.tar.gz}  | awk -F'/' '{print $NF}')

mkdir -p ${PXB24_WORKDIR}/target
mkdir -p ${PXB80_WORKDIR}/target
tar -xzf $PXB24_WORKDIR/$PXB24_TAR --exclude='man' --exclude='*-test' -C ${PXB24_WORKDIR}/target
tar -xzf $PXB80_WORKDIR/$PXB80_TAR --exclude='man' --exclude='*-test' -C ${PXB80_WORKDIR}/target

mv ${PXB24_WORKDIR}/target/$(ls ${PXB24_WORKDIR}/target | grep percona-xtrabackup-2) ${PXB24_WORKDIR}/target/pxb-2.4
mv ${PXB80_WORKDIR}/target/$(ls ${PXB80_WORKDIR}/target | grep percona-xtrabackup-8) ${PXB80_WORKDIR}/target/pxb-8.0

mkdir -p ${WORKDIR_ABS}/PXC/bin/pxc_extra/pxb-2.4
mkdir -p ${WORKDIR_ABS}/PXC/bin/pxc_extra/pxb-8.0
cp -v -r ${PXB24_WORKDIR}/target/pxb-2.4/{bin,lib} ${WORKDIR_ABS}/PXC/bin/pxc_extra/pxb-2.4
cp -v -r ${PXB80_WORKDIR}/target/pxb-8.0/{bin,lib} ${WORKDIR_ABS}/PXC/bin/pxc_extra/pxb-8.0
# PXB <<<

#
# Galera
export WSREP_PROVIDER=${WORKDIR_ABS}/PXC/lib/libgalera_smm.so

LOG_FILE=${WORKDIR_ABS}/mtr-test.log

cd ${WORKDIR_ABS}/PXC/mysql-test

# >>> temporary patch start
# Temporary patch for execution on Hetzner machines
# Why we need this:
# GCache encryption uses mmap. It may happen that in some Docker environments mmap
# fails. This causes Galera to emit warning, and this causes test to fail.
# Despite of the warning, the functionality works fine.
# Suppression is added to mtr_warnings.sql, but previous versions don't have it.
# So if someone starts from early GCA and tries to build, may hit this problem.
# Add the suppression here.
# Remove this patch one day, when we are far away from the point without suppression
# in mtr_warnings.sql
echo "*****************************************************************************"
echo "Applying temporary patch to mtr_warnings.sql. CONSIDER REMOVING THIS PATCH!!!"
echo "*****************************************************************************"
pushd include
sed -i '/("THE_LAST_SUPPRESSION");/i\
(".*mlock failed. It will still work, but swap pages into the disk, so performance will be affected"),
' mtr_warnings.sql
popd
# <<< temporary patch end

TESTCASE_TIMEOUT=10
# CentOS 7
if [[ -f /opt/rh/devtoolset-8/enable ]]; then
    source /opt/rh/devtoolset-8/enable
fi

# If we are on ubuntu:noble, we need the following hack for PXB-2.4 tarballs
# In official PXC release we have a special build of pxb-2.4 for noble, but unfortunately
# no tarballs available
if [ -f /usr/bin/apt-get ]; then
  DIST=$(lsb_release -sc)
  if [[ ${DIST} == "noble" ]]; then
    sudo ln -s /usr/lib/x86_64-linux-gnu/libaio.so.1t64 /usr/lib/x86_64-linux-gnu/libaio.so.1
  fi
fi

#
# Determine what we've got in the environent
JEMALLOC=$(find /lib* /usr/lib* /usr/local/lib* -type f -name 'libjemalloc.so*' | head -n1)
EATMYDATA=$(find /lib* /usr/lib* /usr/local/lib* -type f -name '*eatmyda*.so*' | head -n1)
OPENSSL_HEADER="/usr/include/openssl/opensslv.h"
OPENSSL_VER=$(grep -o 'define SHLIB_VERSION_NUMBER .*$' ${OPENSSL_HEADER} | awk -F'"' '{print $(NF-1)}' | sed -e 's:[a-z]::g')

if [[ -z "${EATMYDATA}" ]]; then
  echo "No libeatmydata.so lib found"
  exit 1
fi

if [[ -z "${JEMALLOC}" ]]; then
  echo "No jemalloc lib found"
  exit 1
fi

if [[ -n "${MTR_REPEAT}" ]]; then
  MTR_ARGS+=" --repeat=${MTR_REPEAT}"
fi

if [[ "${MTR_ARGS}" == *"--suite=max_parts"* ]]; then
    TESTCASE_TIMEOUT=$((TESTCASE_TIMEOUT * 6))
fi

PARALLEL=$(grep -c ^processor /proc/cpuinfo)
galera_extra_options=
#
# asan/valgrind
if [[ "${ANALYZER_OPTS}" == *WITH_VALGRIND=ON* ]]; then
  MTR_ARGS+=" --valgrind --valgrind-clients --valgrind-option=--leak-check=full --valgrind-option=--show-leak-kinds=all"
  galera_extra_options=" --only-combinations=enc_off"
  [[ ${OPENSSL_VER} < '1.0.2' ]] && export OPENSSL_ia32cap=~0x200000000000000
  # No, MTR runner already has --testcase-timeout * 10
  # TESTCASE_TIMEOUT=$((TESTCASE_TIMEOUT * 6))
  if [[ ${PARALLEL} -gt 1 ]]; then
    PARALLEL=$((PARALLEL/3))
  fi
fi

# hack for too big instances ;)
if [[ ${PARALLEL} -gt 10 ]]; then
  echo "Limit parallel ${PARALLEL} -> 10"
  PARALLEL=10
fi

if [[ "${ANALYZER_OPTS}" == *WITH_*SAN*=ON* ]]; then
    MTR_ARGS+=" --sanitize"
fi

if [[ "${ANALYZER_OPTS}" == *WITH_ASAN=ON* ]]; then
  # detect_odr_violation:
  # If >=2, detect violation of One-Definition-Rule (ODR);
  # If ==1, detect ODR-violation only if the two variables have different sizes
  export ASAN_OPTIONS=allocator_may_return_null=true:detect_odr_violation=1
  # trying to find the proper library
  MYSQLD=$(find ${WORKDIR_ABS}/PXC/bin -name mysqld)
  LIBASAN=$(ldd ${MYSQLD} | grep libasan | awk '{print $3}')
  ADD_TO_LD_PRELOAD="${LIBASAN}:"
fi


#
# execute big tests in separate run
BIG_TEST=0
ONLY_BIG_TEST=0
big_test_extra_option=
only_big_test_extra_option=
if [[ $MTR_ARGS == *"--big-test"* ]]; then
    BIG_TEST=1
    big_test_extra_option="--big-test"
fi
if [[ $MTR_ARGS == *"--only-big-test"* ]]; then
    ONLY_BIG_TEST=1
    BIG_TEST=1
    only_big_test_extra_option="--only-big-test"
fi
MTR_ARGS=${MTR_ARGS//"--big-test"/""}
MTR_ARGS=${MTR_ARGS//"--only-big-test"/""}

#
# unit tests
UNIT_TESTS=0
if [[ $MTR_ARGS == *"--unit-tests-report"* ]]; then
    UNIT_TESTS=1
fi
MTR_ARGS=${MTR_ARGS//"--unit-tests-report"/""}


status=0

#
# adjustments for Valgrind
if [[ "${ANALYZER_OPTS}" == *WITH_VALGRIND=ON* ]]; then
    MYSQLD_ENV=--mysqld-env=\"LD_PRELOAD=${ADD_TO_LD_PRELOAD:-}${EATMYDATA}\"
else
    MYSQLD_ENV=--mysqld-env=\"LD_PRELOAD=${ADD_TO_LD_PRELOAD:-}${JEMALLOC}:${EATMYDATA}\"
fi

#
# This is a hack. SST script fails with LD_LIBRARY=libasan.so. It has to be specified if we are using
# jemalloc/eatmydata.
# Wrap SST script with empty LD_PRELOAD env
if [[ "${ANALYZER_OPTS}" == *WITH_ASAN=ON* ]]; then
    pushd ${WORKDIR_ABS}/PXC/bin
    mv wsrep_sst_xtrabackup-v2 wsrep_sst_xtrabackup-v2.bin

    cat << EOF > wsrep_sst_xtrabackup-v2
#!/bin/bash
export LD_PRELOAD=
${WORKDIR_ABS}/PXC/bin/wsrep_sst_xtrabackup-v2.bin "\$@";
EOF

    chmod a+rx wsrep_sst_xtrabackup-v2
    popd
fi

if [[ -f /etc/redhat-release ]]; then
    sudo yum install -y net-tools netcat
else
    sudo apt update
    sudo apt install -y net-tools netcat-openbsd
fi
ifconfig

mkdir mtr_var

#
# >>>> execute all unit tests at the beginning with main.1st
if [[ $UNIT_TESTS == "1" ]]; then
    tests="main.1st"
    suiteNoSlash="UNIT_TESTS"
    echo "Executing unit tests with $tests"

    df -h
    du /dev/shm
    mount
    ls -la /dev/shm
    cat /proc/meminfo
    start=`date +%s`

    if [[ "${KEYRING_VAULT_MTR}" == 'yes' ]]; then
        MTR_VAULT_ARRAY=(
            MTR_VAULT_ADDRESS=${VAULT_V2_DEV_ADDRESS}
            MTR_VAULT_ADMIN_TOKEN=${VAULT_V2_DEV_ROOT_TOKEN}
            MTR_VAULT_PLUGIN_TOKEN=${VAULT_V2_DEV_MTR_TOKEN}
            MTR_VAULT_VERSION=2
        )
    fi

    env "${MTR_VAULT_ARRAY[@]}" MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
        --parallel=${PARALLEL} \
        --result-file \
        --unit-tests-report \
        ${tests} \
        ${MTR_ARGS} \
        --force \
        --max-test-fail=0 \
        --junit-output=${WORKDIR_ABS}/junit_${suiteNoSlash}.xml \
        --junit-package="${DOCKER_OS}.${CMAKE_BUILD_TYPE}.${suiteNoSlash}" || true

    ln -s $PWD/var $PWD/var_${suiteNoSlash}
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_${suiteNoSlash} $PWD/mtr_var

    killall -9 mysqld || true
    rm -rf $PWD/var_${suiteNoSlash}

    df -h
    du -sh /dev/shm

    end=`date +%s`
    runtime=$((end-start))
    echo KH,UNIT_TESTS,${tests},time,$runtime
fi


# # For replication suites, use less workers. Let's say 3 cpus per worker...
# RPL_PARALLEL_RUN=$((PARALLEL/3))        
# # ...but not less than GALERA_PARALLEL_RUN (to have it still configurable via Jenkins UI)
# if [[ ${RPL_PARALLEL_RUN} -lt ${GALERA_PARALLEL_RUN} ]]; then
#   RPL_PARALLEL_RUN=${GALERA_PARALLEL_RUN}
# fi

# Just use the same parallel as we use for Galera
RPL_PARALLEL_RUN=${GALERA_PARALLEL_RUN}

echo "Limiting workers count for replication suites to ${RPL_PARALLEL_RUN}"

#
# Execute MTR tests
suitesNormal=
suitesBig=
suitesSmall=
suitesReplicationNormal=
suitesReplicationBig=
suitesReplicationSmall=
suitesGaleraNormal=
suitesGaleraBig=
suitesGaleraSmall=

# collect suites
ARRAY_MTR_SUITES=($(echo $MTR_SUITES | sed 's/,/ /g'))
for suite in "${ARRAY_MTR_SUITES[@]}"; do
    only_big_tests_this=0
    only_small_tests_this=0

    # suite may be in form:
    # main
    # main|big
    # main|nobig
    arrSuite=(${suite//|/ })
    suite=${arrSuite[0]}
    big=${arrSuite[1]}

    if [[ "${big}" == "big" ]]; then
        if [[ $BIG_TEST == 0 ]]; then
            continue
        fi
        only_big_tests_this=1
        # only big
    elif [[ "${big}" == "nobig" ]]; then
        # only nobig
        if [[ $ONLY_BIG_TEST == 1 ]]; then
            continue
        fi
        only_small_tests_this=1
    else
        # normal (big + nobig)
        only_big_tests_this=0
        only_small_tests_this=0
    fi

    if [[ "${ANALYZER_OPTS}" == *WITH_VALGRIND=ON* ]]; then
      if [[ "$suite" == "galera_encryption" ]]; then
        echo "Skipping $suite suite for Valgrind build"
        continue
      fi
    fi

    # The idea behind passing 'parallel' value is the following:
    # 1. By default we use above auto-detected value
    # 2. It is possible to pass --parallel=N via MTR_ARGS, which should override 1
    # 3. For galera and rpl tests we still need to force --parallel to lower number than auto-detected or passed via MTR_ARGS
    #
    # execute() function uses passes parameters to mtr framework in the order:
    # 1. --parallel=<autodetected/galera_parallel/rpl_parallel>
    # 2. MTR_ARGS
    # 3. extraOptions
    #
    # That's why we need to force --parallel value, we pass it via extraOptions (3rd parameter)
    if [[ $only_big_tests_this == "1" ]]; then
        if [[ "$suite" == *"galera"* || "${suite}" == "wsrep" ]]; then
            executeOneSuite "$suite" "${GALERA_PARALLEL_RUN}" "--only-big-test $galera_extra_options --parallel=${GALERA_PARALLEL_RUN}" "big"
            suitesGaleraBig+="$suite,"
        elif [[ "${suite}" == "group_replication" || "${suite}" == *rpl* ]]; then
            executeOneSuite "$suite" "${RPL_PARALLEL_RUN}" "--only-big-test --parallel=${RPL_PARALLEL_RUN}" "big"
            suitesReplicationBig+="$suite,"
        else
            executeOneSuite "$suite" "${PARALLEL}" "--only-big-test" "big"
            suitesBig+="$suite,"
    fi
    elif [[ $only_small_tests_this == "1" ]]; then
        if [[ "$suite" == *"galera"* || "${suite}" == "wsrep" ]]; then
            executeOneSuite "$suite" "${GALERA_PARALLEL_RUN}" "$galera_extra_options --parallel=${GALERA_PARALLEL_RUN}" "small"
            suitesGaleraSmall+="$suite,"
        elif [[ "${suite}" == "group_replication" || "${suite}" == *rpl* ]]; then
            executeOneSuite "$suite" "${RPL_PARALLEL_RUN}" "--parallel=${RPL_PARALLEL_RUN}" "small"
            suitesReplicationSmall+="$suite,"
        else
            executeOneSuite "$suite" "${PARALLEL}" "" "small"
            suitesSmall+="$suite,"
        fi
    else
        if [[ "$suite" == *"galera"* || "${suite}" == "wsrep" ]]; then
            executeOneSuite "$suite" "${GALERA_PARALLEL_RUN}" "${big_test_extra_option} $galera_extra_options --parallel=${GALERA_PARALLEL_RUN}"
            suitesGaleraNormal+="$suite,"
        elif [[ "${suite}" == "group_replication" || "${suite}" == *rpl* ]]; then
            executeOneSuite "$suite" "${RPL_PARALLEL_RUN}" "${big_test_extra_option} --parallel=${RPL_PARALLEL_RUN}"
            suitesReplicationNormal+="$suite,"
        else
            executeOneSuite "$suite" "${PARALLEL}" "${big_test_extra_option}"
            suitesNormal+="$suite,"
        fi
    fi
done

# Execute suites
if [[ ${EXECUTE_SUITES_ONE_BY_ONE} == 0 ]]; then
  echo "MTR normal suites: $suitesNormal"
  echo "MTR big suites: $suitesBig"
  echo "MTR small suites: $suitesSmall"
  echo "MTR replication normal suites: $suitesReplicationNormal"
  echo "MTR replication big suites: $suitesReplicationBig"
  echo "MTR replication small suites: $suitesReplicationSmall"
  echo "MTR galera normal suites: $suitesGaleraNormal"
  echo "MTR galera big suites: $suitesGaleraBig"
  echo "MTR galera small suites: $suitesGaleraSmall"

  executeSuites "$suitesNormal" "${PARALLEL}" "${big_test_extra_option}"
  executeSuites "$suitesBig" "${PARALLEL}" "--only-big-test"
  executeSuites "$suitesSmall" "${PARALLEL}" ""

  # For galera tests, force --parallel force the value via 2nd parameter
  executeSuites "$suitesGaleraNormal" "${GALERA_PARALLEL_RUN}" "${big_test_extra_option} $galera_extra_options --parallel=${GALERA_PARALLEL_RUN}"
  executeSuites "$suitesGaleraBig" "${GALERA_PARALLEL_RUN}" "--only-big-test $galera_extra_options --parallel=${GALERA_PARALLEL_RUN}"
  executeSuites "$suitesGaleraSmall" "${GALERA_PARALLEL_RUN}" "$galera_extra_options --parallel=${GALERA_PARALLEL_RUN}"

  # For replication tests, force --parallel force the value via 2nd parameter
  executeSuites "$suitesReplicationNormal" "${RPL_PARALLEL_RUN}" "${big_test_extra_option} --parallel=${RPL_PARALLEL_RUN}"
  executeSuites "$suitesReplicationBig" "${RPL_PARALLEL_RUN}" "--only-big-test --parallel=${RPL_PARALLEL_RUN}"
  executeSuites "$suitesReplicationSmall" "${RPL_PARALLEL_RUN}" "--parallel=${RPL_PARALLEL_RUN}"
fi

#
# CI FS tests
if [[ "${CI_FS_MTR}" = 'yes' ]]; then
    echo "Running CI FS tests"
    start=`date +%s`

    # For CIFS tests we have a small disk. Limit the parallel option, even if
    # it was explicitly set in MTR_ARGS
    if [[ ${PARALLEL} -gt 10 ]]; then
    echo "Limit parallel ${PARALLEL} -> 10"
    PARALLEL=10
    fi

    # no --mem allowed if vardir specified
    MTR_ARGS=${MTR_ARGS//"--mem"/""}

    if [[ $BIG_TEST == "1" ]]; then
        MTR_ARGS+=" --big-test"
    fi

    # Collect all CI_FS tests
    CI_TESTS=$(grep --exclude="*.inc" --exclude="*.log" -rl . -e include/have_case_insensitive_file_system.inc | awk -F '/' '{print $(NF-2)"."$NF}' | sed 's/\.test//g' | sed 's/^\./main/g')
    # Requested in PS-7602
    CI_TESTS+=" information_schema.i_s_schema_definition_debug"

    # Filter out disabled tests
    # Skip lines starting with #
    # Grab until whitespace or :
    DISABLED_TESTS=$(grep -P -o collections/disabled.def -e'^\s*[^#][^:\s]*')

    set +x
    for CURRENT_TEST in $DISABLED_TESTS; do
        CI_TESTS=$(echo $CI_TESTS | sed "s/\b${CURRENT_TEST}\b//g")
    done
    set -x

    MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
        --result-file \
        --force ${MYSQLD_ENV} \
        --max-test-fail=0 \
        --suite-timeout=9999 \
        --testcase-timeout=${TESTCASE_TIMEOUT} \
        ${MTR_ARGS} \
        --tmpdir="/tmp/ps_mtr_tempdir" \
        --vardir="/tmp/ci_disk_dir/var" \
        --parallel=${PARALLEL} \
        ${CI_TESTS} \
        --junit-output=${WORKDIR_ABS}/junit_ci_fs.xml \
        --junit-package="${DOCKER_OS}.${CMAKE_BUILD_TYPE}.ci_fs" | tee -a ${LOG_FILE} || true

    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' /tmp/ci_disk_dir $PWD/mtr_var

    end=`date +%s`
    runtime=$((end-start))
    echo KH,SUITE_TOTAL,CI_FS_tests,time,$runtime
fi

#
# standalone tests
if [[ -n "${MTR_STANDALONE_TESTS}" ]]; then
    echo "Running standalone tests"
    MTR_ARGS+=" --big-test"
    suiteNoSlash="standalone_tests"

    start=`date +%s`

    df -h
    du /dev/shm
    mount
    ls -la /dev/shm
    cat /proc/meminfo

    MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
        --result-file \
        --force ${MYSQLD_ENV} \
        --max-test-fail=0 \
        --suite-timeout=9999 --parallel=${MTR_STANDALONE_TESTS_PARALLEL} \
        --port-group-size=20 \
        --testcase-timeout=${TESTCASE_TIMEOUT} \
        ${MTR_ARGS} \
        --junit-output=${WORKDIR_ABS}/junit_${suiteNoSlash}.xml \
        --junit-package="${DOCKER_OS}.${CMAKE_BUILD_TYPE}.${suiteNoSlash}" ${MTR_STANDALONE_TESTS} | tee -a ${LOG_FILE} || true

    ln -s $PWD/var $PWD/var_${suiteNoSlash}
    rsync -a -L --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_${suiteNoSlash} $PWD/mtr_var

    killall -9 mysqld || true
    rm -rf $PWD/var_${suiteNoSlash}

    df -h
    du -sh /dev/shm

    end=`date +%s`
    runtime=$((end-start))
    echo KH,SUITE_TOTAL,${suite},time,$runtime
fi

# Convert Latin1(ISO-8859-1) into browser readable UTF-8
for file in $(find ${WORKDIR_ABS}/ -maxdepth 1 -name "*.xml"); do
    iconv -c -t UTF-8 ${file} | tr -cd '[:print:]\n\r' > ${file}-converted
    mv ${file}-converted ${file}
done

exit $status
