#!/bin/bash
#
# Execute this tool to test binary releases
#
#  possible jenkins vars:
#      CMAKE_BUILD_TYPE = (RelWithDebInfo Debug)
#      DEFAULT_TESTING = (yes no)
#      QA_ARGS

set -o errexit
set -o xtrace

WORKDIR_ABS=$(cd ${1:-./build/pxc}; pwd -P)
rm -fr ${WORKDIR_ABS}/PXC
mkdir -p ${WORKDIR_ABS}/PXC/sql
rm -fr ${WORKDIR_ABS}/PXB
mkdir -p ${WORKDIR_ABS}/PXB
tar -C ${WORKDIR_ABS}/PXC --strip-components=1 -zxpf $(ls $WORKDIR_ABS/pxc56*.tar.gz | head -1)
tar -C ${WORKDIR_ABS}/PXB --strip-components=1 -zxpf $(ls $WORKDIR_ABS/pxb23*.tar.gz | head -1)

#export WSREP_PROVIDER=${WORKDIR_ABS}/PXC/lib/libgalera_smm.so
git clone https://github.com/Percona-QA/pxc-qa -b dev-branch ${WORKDIR_ABS}/pxc-qa
sed -i "s|^[ \t]*basedir[ \t]*=.*$|basedir = ${WORKDIR_ABS}/PXC|" ${WORKDIR_ABS}/pxc-qa/config.ini
sed -i "s|^[ \t]*workdir[ \t]*=.*$|workdir = ${WORKDIR_ABS}|" ${WORKDIR_ABS}/pxc-qa/config.ini

sudo cp ${WORKDIR_ABS}/PXB/bin/* /usr/bin/

#cd ${WORKDIR_ABS}/PXC/mysql-test
TESTCASE_TIMEOUT=30
PARALLEL=$(grep -c ^processor /proc/cpuinfo)
which python
# CentOS 6 & 7
sudo yum list | grep python3
sudo yum install -y python3 sysbench perl-DBD-mysql
sudo pip3 install mysql-connector
cd ${WORKDIR_ABS}/pxc-qa
status=0
#

if [[ -z "${QA_ARGS}" ]]; then
  QA_ARGS="--suite=replication"
fi
# Running Replication QA job
export PYTHONIOENCODING=utf-8
python3 ${WORKDIR_ABS}/pxc-qa/qa_framework.py ${QA_ARGS} | tee ${WORKDIR_ABS}/qa_framework.output || status=$?

exit $status
