#!/bin/bash
#
# Execute this tool to test binary releases
#
#  possible jenkins vars:
#      CMAKE_BUILD_TYPE = (RelWithDebInfo Debug)
#      DEFAULT_TESTING = (yes no)
#      MTR_ARGS
#      MTR_REPEAT
#      FULL_MTR = (yes no)
#      GALERA_PARALLEL_RUN
#      MTR_SUITES
#      PARALLEL_RUN

set -o errexit
set -o xtrace

WORKDIR_ABS=$(cd ${1:-./build/pxc}; pwd -P)
rm -fr ${WORKDIR_ABS}/PXC
mkdir -p ${WORKDIR_ABS}/PXC/sql
tar -C ${WORKDIR_ABS}/PXC --strip-components=1 -zxpf $(ls $WORKDIR_ABS/*.tar.gz | head -1)

export WSREP_PROVIDER=${WORKDIR_ABS}/PXC/lib/libgalera_smm.so
cd ${WORKDIR_ABS}/PXC/mysql-test
TESTCASE_TIMEOUT=30
# CentOS 7
if [[ -f /opt/rh/devtoolset-8/enable ]]; then
    source /opt/rh/devtoolset-8/enable
fi

JEMALLOC=$(find /lib* /usr/lib* /usr/local/lib* -type f -name 'libjemalloc.so*' | head -n1)
EATMYDATA=$(find /lib* /usr/lib* /usr/local/lib* -type f -name '*eatmyda*.so*' | head -n1)

if [[ -z "${EATMYDATA}" ]]; then
  echo "No libeatmydata.so lib found"
  exit 1
fi

if [[ -z "${JEMALLOC}" ]]; then
  echo "No jemalloc lib found"
  exit 1
fi
MTR_ARGS+="  --big-test "


if [[ -n "${MTR_REPEAT}" ]]; then
  MTR_ARGS+=" --repeat=${MTR_REPEAT}"
fi

if [[ "${MTR_ARGS}" == *"--suite=max_parts"* ]]; then
    TESTCASE_TIMEOUT=$((TESTCASE_TIMEOUT * 3))
fi

if [[ $MTR_ARGS == *"--big-test"* ]] || [[ $MTR_ARGS == *"--only-big-test"* ]]; then
    TESTCASE_TIMEOUT=$((TESTCASE_TIMEOUT * 2))
fi

status=0
#
# Running MTR test cases
if [[ "${DEFAULT_TESTING}" != "no" ]]; then

    if [[ "${ANALYZER_OPTS}" == *WITH_VALGRIND=ON* ]]; then
        MYSQLD_ENV="${ADD_TO_LD_PRELOAD:-}${EATMYDATA}"
    else
        MYSQLD_ENV="${ADD_TO_LD_PRELOAD:-}${JEMALLOC}:${EATMYDATA}"
    fi
    mkdir mtr_var
    if [ ${FULL_MTR} == "no" ]; then
        ARRAY_MTR_SUITES=($(echo $MTR_SUITES | sed 's/,/ /g'))
        for suite in "${ARRAY_MTR_SUITES[@]}"; do
	        if [[ "$suite" == *"galera"* ]]; then
	            WORKER=$GALERA_PARALLEL_RUN
			else
	            WORKER=$PARALLEL_RUN
			fi
	        echo "Running MTR suite: $suite"
	        mkdir $PWD/var_${suite}

	        MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
	           --result-file --suite=$suite \
	           --force --xml-report=${WORKDIR_ABS}/${suite}_mtr.xml \
	           --max-test-fail=0 \
	           --suite-timeout=9999 --parallel $WORKER \
	           --port-group-size=20 --vardir=$PWD/var_${suite} \
	           --testcase-timeout=${TESTCASE_TIMEOUT} \
               ${MTR_ARGS} \
	           | tee ${WORKDIR_ABS}/${suite}_mtr.output || status=$?
            mv $PWD/var_${suite} $PWD/mtr_var
	        killall -9 mysqld || true
		    sed -i '1d' ${WORKDIR_ABS}/${suite}_mtr.xml
		    sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/${suite}_mtr.xml
		    sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/${suite}_mtr.xml > ${WORKDIR_ABS}/${suite}_junit.tmp
		    sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/${suite}_junit.tmp >  ${WORKDIR_ABS}/${suite}_junit1.tmp
		    sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/${suite}_junit1.tmp >  ${WORKDIR_ABS}/${suite}_junit2.tmp
            perl -p -0777 -e 's@<failure message=.*?">@<failure message="Test failed:...">@sg' ${WORKDIR_ABS}/${suite}_junit2.tmp > ${WORKDIR_ABS}/${suite}_junit.xml
		    rm -f ${WORKDIR_ABS}/${suite}_junit*.tmp ${WORKDIR_ABS}/${suite}_mtr.xml
		done
    else
        echo "Running full MTR"
		mkdir var

        MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
           --result-file \
           --force --xml-report=${WORKDIR_ABS}/mtr.xml \
           --max-test-fail=0 \
           --suite-timeout=9999 --parallel $PARALLEL_RUN \
           --port-group-size=20 --vardir=var \
           --testcase-timeout=${TESTCASE_TIMEOUT} \
           ${MTR_ARGS} \
           | tee ${WORKDIR_ABS}/mtr.output || status=$?
        mv $PWD/var $PWD/mtr_var
        killall -9 mysqld || true
	    sed -i '1d' ${WORKDIR_ABS}/mtr.xml
	    sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/mtr.xml
	    sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/mtr.xml > ${WORKDIR_ABS}/junit.tmp
	    sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/junit.tmp >  ${WORKDIR_ABS}/junit1.tmp
	    sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/junit1.tmp >  ${WORKDIR_ABS}/junit2.tmp
        perl -p -0777 -e 's@<failure message=.*?">@<failure message="Test failed:...">@sg' ${WORKDIR_ABS}/junit2.tmp > ${WORKDIR_ABS}/junit.xml
	    rm -f ${WORKDIR_ABS}/junit*.tmp ${WORKDIR_ABS}/mtr.xml
    fi
fi

exit $status
