#!/bin/bash
#
# Execute this tool to test binary releases
#
#  possible jenkins vars:
#      CMAKE_BUILD_TYPE = (RelWithDebInfo Debug)
#      DEFAULT_TESTING = (yes no)
#      MTR_ARGS
#      MTR_REPEAT
#      FULL_MTR = (yes no)
#      GALERA_PARALLEL_RUN
#      MTR_SUITES
#      PARALLEL_RUN

set -o errexit
set -o xtrace

WORKDIR_ABS=$(cd ${1:-./build/pxc}; pwd -P)
rm -fr ${WORKDIR_ABS}/PXC
mkdir -p ${WORKDIR_ABS}/PXC/sql
tar -C ${WORKDIR_ABS}/PXC --strip-components=1 -zxpf $(ls $WORKDIR_ABS/*.tar.gz | head -1)

export WSREP_PROVIDER=${WORKDIR_ABS}/PXC/lib/libgalera_smm.so
cd ${WORKDIR_ABS}/PXC/mysql-test
TESTCASE_TIMEOUT=30
# CentOS 6 & 7
if [[ -f /opt/rh/devtoolset-7/enable ]]; then
    source /opt/rh/devtoolset-7/enable
fi

JEMALLOC=$(find /lib* /usr/lib* /usr/local/lib* -type f -name 'libjemalloc.so*' | head -n1)
EATMYDATA=$(find /lib* /usr/lib* /usr/local/lib* -type f -name '*eatmyda*.so*' | head -n1)

if [[ -z "${EATMYDATA}" ]]; then
  echo "No libeatmydata.so lib found"
  exit 1
fi

if [[ -z "${JEMALLOC}" ]]; then
  echo "No jemalloc lib found"
  exit 1
fi
MTR_ARGS+="  --big-test "


if [[ -n "${MTR_REPEAT}" ]]; then
  MTR_ARGS+=" --repeat=${MTR_REPEAT}"
fi

if [[ "${MTR_ARGS}" == *"--suite=max_parts"* ]]; then
    TESTCASE_TIMEOUT=$((TESTCASE_TIMEOUT * 3))
fi

if [[ $MTR_ARGS == *"--big-test"* ]] || [[ $MTR_ARGS == *"--only-big-test"* ]]; then
    TESTCASE_TIMEOUT=$((TESTCASE_TIMEOUT * 2))
fi

status=0
#
# Running MTR test cases
if [[ "${DEFAULT_TESTING}" != "no" ]]; then

    if [[ "${ANALYZER_OPTS}" == *WITH_VALGRIND=ON* ]]; then
        MYSQLD_ENV="${ADD_TO_LD_PRELOAD:-}${EATMYDATA}"
    else
        MYSQLD_ENV="${ADD_TO_LD_PRELOAD:-}${JEMALLOC}:${EATMYDATA}"
    fi
    if [ ${FULL_MTR} == "no" ]; then
        # galera suite
        if echo "$MTR_SUITES" | grep -Ewq "galera"; then
           mkdir var1
           MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
              --result-file --suite=galera \
              ${MTR_ARGS} \
              --force --xml-report=${WORKDIR_ABS}/galera_mtr.xml \
              --max-test-fail=0 \
              --suite-timeout=9999 --parallel $GALERA_PARALLEL_RUN \
              --port-group-size=20 --vardir=var1 \
              --testcase-timeout=${TESTCASE_TIMEOUT} \
              | tee ${WORKDIR_ABS}/galera_mtr.output || status=$?
    
            killall -9 mysqld || true
		    sed -i '1d' ${WORKDIR_ABS}/galera_mtr.xml
		    sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/galera_mtr.xml
		    sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/galera_mtr.xml > ${WORKDIR_ABS}/galera_mtr.tmp
		    sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/galera_mtr.tmp >  ${WORKDIR_ABS}/galera_mtr1.tmp
		    sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/galera_mtr1.tmp >  ${WORKDIR_ABS}/galera_junit.xml
		    rm -f ${WORKDIR_ABS}/galera_mtr*.tmp ${WORKDIR_ABS}/galera_mtr.xml
        fi
    
        # galera_3nodes suite
        if echo "$MTR_SUITES" | grep -Ewq "galera_3nodes"; then
           mkdir var2
           MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
              --result-file --suite=galera_3nodes \
              ${MTR_ARGS} \
              --force --xml-report=${WORKDIR_ABS}/galera3_mtr.xml \
              --max-test-fail=0 \
              --suite-timeout=9999 --parallel $GALERA_PARALLEL_RUN \
              --port-group-size=20 --vardir=var2 \
              --testcase-timeout=${TESTCASE_TIMEOUT} \
              | tee ${WORKDIR_ABS}/galera3_mtr.output || status=$?
    
            killall -9 mysqld || true
		    sed -i '1d' ${WORKDIR_ABS}/galera3_mtr.xml
		    sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/galera3_mtr.xml
		    sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/galera3_mtr.xml > ${WORKDIR_ABS}/galera3_mtr.tmp
		    sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/galera3_mtr.tmp >  ${WORKDIR_ABS}/galera3_mtr1.tmp
		    sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/galera3_mtr1.tmp >  ${WORKDIR_ABS}/galera3_junit.xml
		    rm -f ${WORKDIR_ABS}/galera3_mtr*.tmp ${WORKDIR_ABS}/galera3_mtr.xml
        fi

        # galera_sr suite
        if echo "$MTR_SUITES" | grep -Ewq "galera_sr"; then
           mkdir var3
           MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
              --result-file --suite=galera_sr \
              ${MTR_ARGS} \
              --force --xml-report=${WORKDIR_ABS}/galera_sr_mtr.xml \
              --max-test-fail=0 \
              --suite-timeout=9999 --parallel $GALERA_PARALLEL_RUN \
              --port-group-size=20 --vardir=var3 \
              --testcase-timeout=${TESTCASE_TIMEOUT} \
              | tee ${WORKDIR_ABS}/galera_sr_mtr.output || status=$?
    
            killall -9 mysqld || true
		    sed -i '1d' ${WORKDIR_ABS}/galera_sr_mtr.xml
		    sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/galera_sr_mtr.xml
		    sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/galera_sr_mtr.xml > ${WORKDIR_ABS}/galera_sr_mtr.tmp
		    sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/galera_sr_mtr.tmp >  ${WORKDIR_ABS}/galera_sr_mtr1.tmp
		    sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/galera_sr_mtr1.tmp >  ${WORKDIR_ABS}/galera_sr_junit.xml
		    rm -f ${WORKDIR_ABS}/galera_sr_mtr*.tmp ${WORKDIR_ABS}/galera_sr_mtr.xml
        fi
		
        # galera_3nodes_sr suite
        if echo "$MTR_SUITES" | grep -Ewq "galera_3nodes_sr"; then
           mkdir var4
           MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
              --result-file --suite=galera_3nodes_sr \
              ${MTR_ARGS} \
              --force --xml-report=${WORKDIR_ABS}/galera3_sr_mtr.xml \
              --max-test-fail=0 \
              --suite-timeout=9999 --parallel $GALERA_PARALLEL_RUN \
              --port-group-size=20 --vardir=var4 \
              --testcase-timeout=${TESTCASE_TIMEOUT} \
              | tee ${WORKDIR_ABS}/galera3_sr_mtr.output || status=$?
    
            killall -9 mysqld || true
		    sed -i '1d' ${WORKDIR_ABS}/galera3_sr_mtr.xml
		    sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/galera3_sr_mtr.xml
		    sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/galera3_sr_mtr.xml > ${WORKDIR_ABS}/galera3_sr_mtr.tmp
		    sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/galera3_sr_mtr.tmp >  ${WORKDIR_ABS}/galera3_sr_mtr1.tmp
		    sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/galera3_sr_mtr1.tmp >  ${WORKDIR_ABS}/galera3_sr_junit.xml
		    rm -f ${WORKDIR_ABS}/galera3_sr_mtr*.tmp ${WORKDIR_ABS}/galera3_sr_mtr.xml
        fi
		
        # sys_vars suite
        if echo "$MTR_SUITES" | grep -Ewq "sys_vars"; then
           mkdir var5
           MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
              --result-file --suite=sys_vars \
              ${MTR_ARGS} \
              --force --xml-report=${WORKDIR_ABS}/sys_vars.xml \
              --max-test-fail=0 \
              --suite-timeout=9999 --parallel $PARALLEL_RUN \
              --port-group-size=20 --vardir=var5 \
              --testcase-timeout=${TESTCASE_TIMEOUT} \
              | tee ${WORKDIR_ABS}/sys_vars.output || status=$?
    		  
            killall -9 mysqld || true
		    sed -i '1d' ${WORKDIR_ABS}/sys_vars.xml
		    sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/sys_vars.xml
		    sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/sys_vars.xml > ${WORKDIR_ABS}/sys_vars.tmp
		    sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/sys_vars.tmp >  ${WORKDIR_ABS}/sys_vars1.tmp
		    sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/sys_vars1.tmp >  ${WORKDIR_ABS}/sys_vars_junit.xml
		    rm -f ${WORKDIR_ABS}/sys_vars*.tmp ${WORKDIR_ABS}/sys_vars.xml
        fi
    else
        echo "Running full MTR"
        mkdir var1
        MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
           --result-file \
           ${MTR_ARGS} \
           --force --xml-report=${WORKDIR_ABS}/mtr.xml \
           --max-test-fail=0 \
           --suite-timeout=9999 --parallel $GALERA_PARALLEL_RUN \
           --port-group-size=20 --vardir=var1 \
           --testcase-timeout=${TESTCASE_TIMEOUT} \
           | tee ${WORKDIR_ABS}/mtr.output || status=$?
    
        killall -9 mysqld || true
	    sed -i '1d' ${WORKDIR_ABS}/mtr.xml
	    sed -i '/<!\[CDATA/,/]]>/d' ${WORKDIR_ABS}/mtr.xml
	    sed -r 's/comment=.*.\/>/\/>/' ${WORKDIR_ABS}/mtr.xml > ${WORKDIR_ABS}/junit.tmp
	    sed -r 's/status=\"skipped\".*.\/>/ > <skipped \/> <\/testcase>/' ${WORKDIR_ABS}/junit.tmp >  ${WORKDIR_ABS}/junit1.tmp
	    sed -r 's/status=\"disabled\".*.\/>/ > <disabled \/> <\/testcase>/' ${WORKDIR_ABS}/junit1.tmp >  ${WORKDIR_ABS}/junit.xml
	    rm -f ${WORKDIR_ABS}/junit*.tmp ${WORKDIR_ABS}/mtr.xml
    fi
fi

exit $status
