# aws cloudformation --region us-east-1 create-stack --template-body file://IaC/JenkinsArtifactoryIAM --capabilities CAPABILITY_NAMED_IAM --stack-name jenkins-artifactory --tags Key=iit-billing-tag,Value=jenkins-artifactory
---
AWSTemplateFormatVersion: 2010-09-09
Resources:

  JenkinsArtifactoryUser: # create standalone user for Cloud Jenkins AWS_STASH jenkins jobs
    Type: AWS::IAM::User
    Properties:
      UserName: "jenkins-artifactory-user"
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::119175775298:policy/jenkins-artifactory
      - arn:aws:iam::aws:policy/AmazonElasticContainerRegistryPublicReadOnly
      Policies:
        - PolicyName: ECRPrivateAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: 'arn:aws:ecr:us-east-1:119175775298:repository/perconalab/percona-postgresql-operator'
                Action:
                - ecr:GetAuthorizationToken
                - ecr:BatchCheckLayerAvailability
                - ecr:GetDownloadUrlForLayer
                - ecr:GetRepositoryPolicy
                - ecr:DescribeRepositories
                - ecr:ListImages
                - ecr:DescribeImages
                - ecr:BatchGetImage
                - ecr:GetLifecyclePolicy
                - ecr:GetLifecyclePolicyPreview
                - ecr:ListTagsForResource
                - ecr:DescribeImageScanFindings
                - ecr:InitiateLayerUpload
                - ecr:UploadLayerPart
                - ecr:CompleteLayerUpload
                - ecr:PutImage
              - Effect: Allow
                Resource: 'arn:aws:ecr:us-east-1:119175775298:repository/percona/percona-postgresql-operator'
                Action:
                - ecr:GetAuthorizationToken
                - ecr:BatchCheckLayerAvailability
                - ecr:GetDownloadUrlForLayer
                - ecr:GetRepositoryPolicy
                - ecr:DescribeRepositories
                - ecr:ListImages
                - ecr:DescribeImages
                - ecr:BatchGetImage
                - ecr:GetLifecyclePolicy
                - ecr:GetLifecyclePolicyPreview
                - ecr:ListTagsForResource
                - ecr:DescribeImageScanFindings
                - ecr:InitiateLayerUpload
                - ecr:UploadLayerPart
                - ecr:CompleteLayerUpload
                - ecr:PutImage
        - PolicyName: GetAuthToken
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Resource:
              - '*'
              Action:
              - ecr:GetAuthorizationToken
              - sts:GetServiceBearerToken
      Tags:
      - Key: iit-billing-tag
        Value: jenkins-artifactory-user

  JenkinsArtifactoryUserKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref JenkinsArtifactoryUser

Outputs:
  JenkinsArtifactoryUserAccessKey:
    Description: JenkinsArtifactory AccessKey
    Value: !Ref JenkinsArtifactoryUserKey
  JenkinsArtifactoryUserSecretKey:
    Description: JenkinsArtifactory SecretAccessKey
    Value: !GetAtt JenkinsArtifactoryUserKey.SecretAccessKey