---
AWSTemplateFormatVersion: 2010-09-09
Description: "Spot SNS termination alerting"
Parameters: {}
Mappings: {}
Conditions: 
  CreateForPMM: !Or [!Equals [!Ref AWS::Region, 'us-east-1'], !Equals [!Ref AWS::Region, 'us-east-2']]
  CreateForREL: !Not [!Condition CreateForPMM]
Resources:

  SNSTopicREL:
    Condition: CreateForREL
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNS Topic for EC2 Spot Instance Interruption Notices
      Subscription:
      - Endpoint: "slava.sarzhan@percona.com"
        Protocol: email
      - Endpoint: "evgeniy.patlan@percona.com"
        Protocol: email
      - Endpoint: "oleksandr.miroshnychenko@percona.com"
        Protocol: email

  SNSTopicPMM:
    Condition: CreateForPMM
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNS Topic for EC2 Spot Instance Interruption Notices
      Subscription:
      - Endpoint: "evgeniy.patlan@percona.com"
        Protocol: email
      - Endpoint: "oleksandr.miroshnychenko@percona.com"
        Protocol: email
      - Endpoint: "alexander.tymchuk@percona.com"
        Protocol: email
      - Endpoint: "nikita.beletskii@percona.com"
        Protocol: email

  TerminationSNSPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: !If [CreateForPMM, !GetAtt SNSTopicPMM.TopicName, !GetAtt SNSTopicREL.TopicName]
        Statement:
        - Action: sns:Publish
          Effect: Allow
          Principal:
            Service:
            - events.amazonaws.com
          Resource: !If [CreateForPMM, !Ref SNSTopicPMM, !Ref SNSTopicREL]
        Version: '2012-10-17'
      Topics:
      - !If [CreateForPMM, !Ref SNSTopicPMM, !Ref SNSTopicREL]

  TerminationRule1: # notify about instance interruption from aws side
    Type: AWS::Events::Rule
    Properties:
      Description: EC2 Spot Instance Interruption Warning
      EventPattern:
        source:
          - aws.ec2
        detail-type:
          - EC2 Spot Instance Interruption Warning
      State: ENABLED
      Targets:
        - Arn: !If [CreateForPMM, !Ref SNSTopicPMM, !Ref SNSTopicREL]
          Id: !If [CreateForPMM, !GetAtt SNSTopicPMM.TopicName, !GetAtt SNSTopicREL.TopicName]
Outputs:
  TerminationSNSTopic:
    Description: SNS topic ARN
    Value: !If [CreateForPMM, !Ref SNSTopicPMM, !Ref SNSTopicREL]
