---
AWSTemplateFormatVersion: 2010-09-09
Description: "Spot SNS termination alerting"
Parameters: {}
Mappings: {}
Resources:

  TerminationSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNS Topic for EC2 Spot Instance Interruption Notices
      Subscription:
      - Endpoint: "illia.pshonkin@percona.com"
        Protocol: email
      - Endpoint: "mykola.marzhan@percona.com"
        Protocol: email
      - Endpoint: "slava.sarzhan@percona.com"
        Protocol: email
      - Endpoint: "evgeniy.patlan@percona.com"
        Protocol: email

  TerminationSNSPolicy:
    Type: AWS::SNS::TopicPolicy
    DependsOn: TerminationSNSTopic
    Properties:
      PolicyDocument:
        Id:
          Fn::GetAtt:
          - TerminationSNSTopic
          - TopicName
        Statement:
        - Action: sns:Publish
          Effect: Allow
          Principal:
            Service:
            - events.amazonaws.com
          Resource: !Ref TerminationSNSTopic
        Version: '2012-10-17'
      Topics:
      - !Ref TerminationSNSTopic

  TerminationRule1: # notify about instance interruption from aws side
    Type: AWS::Events::Rule
    DependsOn: "TerminationSNSTopic"
    Properties:
      Description: EC2 Spot Instance Interruption Warning
      EventPattern:
        source:
          - aws.ec2
        detail-type:
          - EC2 Spot Instance Interruption Warning
      State: ENABLED
      Targets:
        - Arn: !Ref TerminationSNSTopic
          Id: 
            Fn::GetAtt:
            - TerminationSNSTopic
            - TopicName
Outputs:
  TerminationSNSTopic:
    Description: SNS topic ARN
    Value: !Ref TerminationSNSTopic